// Code generated by ros-gen-go.
// source: TransformStamped.msg
// DO NOT EDIT!
package geometry_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgTransformStamped struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgTransformStamped) Text() string {
	return t.text
}

func (t *_MsgTransformStamped) Name() string {
	return t.name
}

func (t *_MsgTransformStamped) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgTransformStamped) NewMessage() ros.Message {
	m := new(TransformStamped)

	return m
}

var (
	MsgTransformStamped = &_MsgTransformStamped{
		`# This expresses a transform from coordinate frame header.frame_id
# to the coordinate frame child_frame_id
#
# This message is mostly used by the 
# <a href="http://wiki.ros.org/tf">tf</a> package. 
# See its documentation for more information.

Header header
string child_frame_id # the frame id of the child frame
Transform transform
`,
		"geometry_msgs/TransformStamped",
		"b5764a33bfeb3588febc2682852579b0",
	}
)

type TransformStamped struct {
	Header       std_msgs.Header
	ChildFrameId string
	Transform    Transform
}

func (m *TransformStamped) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "string", &m.ChildFrameId); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "Transform", &m.Transform); err != nil {
		return err
	}

	return
}

func (m *TransformStamped) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// ChildFrameId
	if err = ros.DeserializeMessageField(r, "string", &m.ChildFrameId); err != nil {
		return err
	}

	// Transform
	if err = ros.DeserializeMessageField(r, "Transform", &m.Transform); err != nil {
		return err
	}

	return
}
