// Code generated by ros-gen-go.
// source: GeographicMap.msg
// DO NOT EDIT!
package geographic_msgs

import (
	"encoding/binary"
	"fmt"
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/msgs/uuid_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgGeographicMap struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGeographicMap) Text() string {
	return t.text
}

func (t *_MsgGeographicMap) Name() string {
	return t.name
}

func (t *_MsgGeographicMap) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGeographicMap) NewMessage() ros.Message {
	m := new(GeographicMap)

	return m
}

var (
	MsgGeographicMap = &_MsgGeographicMap{
		`# Geographic map for a specified region.

Header header            # stamp specifies time
                         # frame_id (normally /map)

uuid_msgs/UniqueID id    # identifier for this map
BoundingBox  bounds      # 2D bounding box containing map

WayPoint[]   points      # way-points
MapFeature[] features    # map features
KeyValue[]   props       # map properties
`,
		"geographic_msgs/GeographicMap",
		"0f4ce6d2ebf9ac9c7c4f3308f6ae0731",
	}
)

type GeographicMap struct {
	Header   std_msgs.Header
	Id       uuid_msgs.UniqueID
	Bounds   BoundingBox
	Points   []WayPoint
	Features []MapFeature
	Props    []KeyValue
}

func (m *GeographicMap) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uuid_msgs/UniqueID", &m.Id); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "BoundingBox", &m.Bounds); err != nil {
		return err
	}

	// Write size little endian
	err = binary.Write(w, binary.LittleEndian, uint32(len(m.Points)))
	if err != nil {
		return fmt.Errorf("could not write array length: %s", err)
	}
	for _, elem := range m.Points {
		if err = ros.SerializeMessageField(w, "WayPoint", &elem); err != nil {
			return err
		}
	}

	// Write size little endian
	err = binary.Write(w, binary.LittleEndian, uint32(len(m.Features)))
	if err != nil {
		return fmt.Errorf("could not write array length: %s", err)
	}
	for _, elem := range m.Features {
		if err = ros.SerializeMessageField(w, "MapFeature", &elem); err != nil {
			return err
		}
	}

	// Write size little endian
	err = binary.Write(w, binary.LittleEndian, uint32(len(m.Props)))
	if err != nil {
		return fmt.Errorf("could not write array length: %s", err)
	}
	for _, elem := range m.Props {
		if err = ros.SerializeMessageField(w, "KeyValue", &elem); err != nil {
			return err
		}
	}

	return
}

func (m *GeographicMap) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Id
	if err = ros.DeserializeMessageField(r, "uuid_msgs/UniqueID", &m.Id); err != nil {
		return err
	}

	// Bounds
	if err = ros.DeserializeMessageField(r, "BoundingBox", &m.Bounds); err != nil {
		return err
	}

	// Points
	{
		// Read size little endian
		var size uint32
		if err = binary.Read(r, binary.LittleEndian, &size); err != nil {
			return fmt.Errorf("cannot read array size for Points: %s", err)
		}
		m.Points = make([]WayPoint, int(size))
		for i := 0; i < int(size); i++ {
			if err = ros.DeserializeMessageField(r, "WayPoint", &m.Points[i]); err != nil {
				return err
			}
		}
	}

	// Features
	{
		// Read size little endian
		var size uint32
		if err = binary.Read(r, binary.LittleEndian, &size); err != nil {
			return fmt.Errorf("cannot read array size for Features: %s", err)
		}
		m.Features = make([]MapFeature, int(size))
		for i := 0; i < int(size); i++ {
			if err = ros.DeserializeMessageField(r, "MapFeature", &m.Features[i]); err != nil {
				return err
			}
		}
	}

	// Props
	{
		// Read size little endian
		var size uint32
		if err = binary.Read(r, binary.LittleEndian, &size); err != nil {
			return fmt.Errorf("cannot read array size for Props: %s", err)
		}
		m.Props = make([]KeyValue, int(size))
		for i := 0; i < int(size); i++ {
			if err = ros.DeserializeMessageField(r, "KeyValue", &m.Props[i]); err != nil {
				return err
			}
		}
	}

	return
}
