// Code generated by ros-gen-go.
// source: GeoPointStamped.msg
// DO NOT EDIT!
package geographic_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgGeoPointStamped struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGeoPointStamped) Text() string {
	return t.text
}

func (t *_MsgGeoPointStamped) Name() string {
	return t.name
}

func (t *_MsgGeoPointStamped) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGeoPointStamped) NewMessage() ros.Message {
	m := new(GeoPointStamped)

	return m
}

var (
	MsgGeoPointStamped = &_MsgGeoPointStamped{
		`Header header
geographic_msgs/GeoPoint position
`,
		"geographic_msgs/GeoPointStamped",
		"ea50d268b03080563c330351a21edc89",
	}
)

type GeoPointStamped struct {
	Header   std_msgs.Header
	Position GeoPoint
}

func (m *GeoPointStamped) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "geographic_msgs/GeoPoint", &m.Position); err != nil {
		return err
	}

	return
}

func (m *GeoPointStamped) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Position
	if err = ros.DeserializeMessageField(r, "geographic_msgs/GeoPoint", &m.Position); err != nil {
		return err
	}

	return
}
