// Code generated by ros-gen-go.
// source: GeoPath.msg
// DO NOT EDIT!
package geographic_msgs

import (
	"encoding/binary"
	"fmt"
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgGeoPath struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGeoPath) Text() string {
	return t.text
}

func (t *_MsgGeoPath) Name() string {
	return t.name
}

func (t *_MsgGeoPath) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGeoPath) NewMessage() ros.Message {
	m := new(GeoPath)

	return m
}

var (
	MsgGeoPath = &_MsgGeoPath{
		`std_msgs/Header header
geographic_msgs/GeoPoseStamped[] poses
`,
		"geographic_msgs/GeoPath",
		"1476008e63041203a89257cfad97308f",
	}
)

type GeoPath struct {
	Header std_msgs.Header
	Poses  []GeoPoseStamped
}

func (m *GeoPath) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// Write size little endian
	err = binary.Write(w, binary.LittleEndian, uint32(len(m.Poses)))
	if err != nil {
		return fmt.Errorf("could not write array length: %s", err)
	}
	for _, elem := range m.Poses {
		if err = ros.SerializeMessageField(w, "geographic_msgs/GeoPoseStamped", &elem); err != nil {
			return err
		}
	}

	return
}

func (m *GeoPath) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// Poses
	{
		// Read size little endian
		var size uint32
		if err = binary.Read(r, binary.LittleEndian, &size); err != nil {
			return fmt.Errorf("cannot read array size for Poses: %s", err)
		}
		m.Poses = make([]GeoPoseStamped, int(size))
		for i := 0; i < int(size); i++ {
			if err = ros.DeserializeMessageField(r, "geographic_msgs/GeoPoseStamped", &m.Poses[i]); err != nil {
				return err
			}
		}
	}

	return
}
