// Code generated by ros-gen-go.
// source: Duration.msg
// DO NOT EDIT!
package std_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

type _MsgDuration struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgDuration) Text() string {
	return t.text
}

func (t *_MsgDuration) Name() string {
	return t.name
}

func (t *_MsgDuration) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgDuration) NewMessage() ros.Message {
	m := new(Duration)

	return m
}

var (
	MsgDuration = &_MsgDuration{
		`duration data
`,
		"std_msgs/Duration",
		"3e286caf4241d664e55f3ad380e2ae46",
	}
)

type Duration struct {
	Data ros.Duration
}

func (m *Duration) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "duration", &m.Data); err != nil {
		return err
	}

	return
}

func (m *Duration) Deserialize(r io.Reader) (err error) {
	// Data
	if err = ros.DeserializeMessageField(r, "duration", &m.Data); err != nil {
		return err
	}

	return
}
