// Code generated by ros-gen-go.
// source: FollowJointTrajectoryActionGoal.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/actionlib_msgs"
	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgFollowJointTrajectoryActionGoal struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFollowJointTrajectoryActionGoal) Text() string {
	return t.text
}

func (t *_MsgFollowJointTrajectoryActionGoal) Name() string {
	return t.name
}

func (t *_MsgFollowJointTrajectoryActionGoal) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFollowJointTrajectoryActionGoal) NewMessage() ros.Message {
	m := new(FollowJointTrajectoryActionGoal)

	return m
}

var (
	MsgFollowJointTrajectoryActionGoal = &_MsgFollowJointTrajectoryActionGoal{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
FollowJointTrajectoryGoal goal
`,
		"control_msgs/FollowJointTrajectoryActionGoal",
		"cff5c1d533bf2f82dd0138d57f4304bb",
	}
)

type FollowJointTrajectoryActionGoal struct {
	Header std_msgs.Header
	GoalId actionlib_msgs.GoalID
	Goal   FollowJointTrajectoryGoal
}

func (m *FollowJointTrajectoryActionGoal) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "actionlib_msgs/GoalID", &m.GoalId); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "FollowJointTrajectoryGoal", &m.Goal); err != nil {
		return err
	}

	return
}

func (m *FollowJointTrajectoryActionGoal) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// GoalId
	if err = ros.DeserializeMessageField(r, "actionlib_msgs/GoalID", &m.GoalId); err != nil {
		return err
	}

	// Goal
	if err = ros.DeserializeMessageField(r, "FollowJointTrajectoryGoal", &m.Goal); err != nil {
		return err
	}

	return
}
