// Code generated by ros-gen-go.
// source: FollowJointTrajectoryActionResult.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/actionlib_msgs"
	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgFollowJointTrajectoryActionResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFollowJointTrajectoryActionResult) Text() string {
	return t.text
}

func (t *_MsgFollowJointTrajectoryActionResult) Name() string {
	return t.name
}

func (t *_MsgFollowJointTrajectoryActionResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFollowJointTrajectoryActionResult) NewMessage() ros.Message {
	m := new(FollowJointTrajectoryActionResult)

	return m
}

var (
	MsgFollowJointTrajectoryActionResult = &_MsgFollowJointTrajectoryActionResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
FollowJointTrajectoryResult result
`,
		"control_msgs/FollowJointTrajectoryActionResult",
		"c4fb3b000dc9da4fd99699380efcc5d9",
	}
)

type FollowJointTrajectoryActionResult struct {
	Header std_msgs.Header
	Status actionlib_msgs.GoalStatus
	Result FollowJointTrajectoryResult
}

func (m *FollowJointTrajectoryActionResult) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "actionlib_msgs/GoalStatus", &m.Status); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "FollowJointTrajectoryResult", &m.Result); err != nil {
		return err
	}

	return
}

func (m *FollowJointTrajectoryActionResult) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Status
	if err = ros.DeserializeMessageField(r, "actionlib_msgs/GoalStatus", &m.Status); err != nil {
		return err
	}

	// Result
	if err = ros.DeserializeMessageField(r, "FollowJointTrajectoryResult", &m.Result); err != nil {
		return err
	}

	return
}
