// Code generated by ros-gen-go.
// source: GripperCommand.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

type _MsgGripperCommand struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGripperCommand) Text() string {
	return t.text
}

func (t *_MsgGripperCommand) Name() string {
	return t.name
}

func (t *_MsgGripperCommand) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGripperCommand) NewMessage() ros.Message {
	m := new(GripperCommand)

	return m
}

var (
	MsgGripperCommand = &_MsgGripperCommand{
		`float64 position
float64 max_effort
`,
		"control_msgs/GripperCommand",
		"680acaff79486f017132a7f198d40f08",
	}
)

type GripperCommand struct {
	Position  float64
	MaxEffort float64
}

func (m *GripperCommand) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "float64", &m.Position); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.MaxEffort); err != nil {
		return err
	}

	return
}

func (m *GripperCommand) Deserialize(r io.Reader) (err error) {
	// Position
	if err = ros.DeserializeMessageField(r, "float64", &m.Position); err != nil {
		return err
	}

	// MaxEffort
	if err = ros.DeserializeMessageField(r, "float64", &m.MaxEffort); err != nil {
		return err
	}

	return
}
