// Code generated by ros-gen-go.
// source: GripperCommandGoal.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

type _MsgGripperCommandGoal struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGripperCommandGoal) Text() string {
	return t.text
}

func (t *_MsgGripperCommandGoal) Name() string {
	return t.name
}

func (t *_MsgGripperCommandGoal) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGripperCommandGoal) NewMessage() ros.Message {
	m := new(GripperCommandGoal)

	return m
}

var (
	MsgGripperCommandGoal = &_MsgGripperCommandGoal{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
GripperCommand command
`,
		"control_msgs/GripperCommandGoal",
		"86fd82f4ddc48a4cb6856cfa69217e43",
	}
)

type GripperCommandGoal struct {
	Command GripperCommand
}

func (m *GripperCommandGoal) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "GripperCommand", &m.Command); err != nil {
		return err
	}

	return
}

func (m *GripperCommandGoal) Deserialize(r io.Reader) (err error) {
	// Command
	if err = ros.DeserializeMessageField(r, "GripperCommand", &m.Command); err != nil {
		return err
	}

	return
}
