// Code generated by ros-gen-go.
// source: JointTrajectoryFeedback.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

type _MsgJointTrajectoryFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgJointTrajectoryFeedback) Text() string {
	return t.text
}

func (t *_MsgJointTrajectoryFeedback) Name() string {
	return t.name
}

func (t *_MsgJointTrajectoryFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgJointTrajectoryFeedback) NewMessage() ros.Message {
	m := new(JointTrajectoryFeedback)

	return m
}

var (
	MsgJointTrajectoryFeedback = &_MsgJointTrajectoryFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

`,
		"control_msgs/JointTrajectoryFeedback",
		"d41d8cd98f00b204e9800998ecf8427e",
	}
)

type JointTrajectoryFeedback struct {
}

func (m *JointTrajectoryFeedback) Serialize(w io.Writer) (err error) {
	return
}

func (m *JointTrajectoryFeedback) Deserialize(r io.Reader) (err error) {
	return
}
