// Code generated by ros-gen-go.
// source: JointTrajectoryActionResult.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/actionlib_msgs"
	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgJointTrajectoryActionResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgJointTrajectoryActionResult) Text() string {
	return t.text
}

func (t *_MsgJointTrajectoryActionResult) Name() string {
	return t.name
}

func (t *_MsgJointTrajectoryActionResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgJointTrajectoryActionResult) NewMessage() ros.Message {
	m := new(JointTrajectoryActionResult)

	return m
}

var (
	MsgJointTrajectoryActionResult = &_MsgJointTrajectoryActionResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
JointTrajectoryResult result
`,
		"control_msgs/JointTrajectoryActionResult",
		"1eb06eeff08fa7ea874431638cb52332",
	}
)

type JointTrajectoryActionResult struct {
	Header std_msgs.Header
	Status actionlib_msgs.GoalStatus
	Result JointTrajectoryResult
}

func (m *JointTrajectoryActionResult) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "actionlib_msgs/GoalStatus", &m.Status); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "JointTrajectoryResult", &m.Result); err != nil {
		return err
	}

	return
}

func (m *JointTrajectoryActionResult) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Status
	if err = ros.DeserializeMessageField(r, "actionlib_msgs/GoalStatus", &m.Status); err != nil {
		return err
	}

	// Result
	if err = ros.DeserializeMessageField(r, "JointTrajectoryResult", &m.Result); err != nil {
		return err
	}

	return
}
