// Code generated by ros-gen-go.
// source: PidState.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgPidState struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgPidState) Text() string {
	return t.text
}

func (t *_MsgPidState) Name() string {
	return t.name
}

func (t *_MsgPidState) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgPidState) NewMessage() ros.Message {
	m := new(PidState)

	return m
}

var (
	MsgPidState = &_MsgPidState{
		`Header header
duration timestep
float64 error
float64 error_dot
float64 p_error
float64 i_error
float64 d_error
float64 p_term
float64 i_term
float64 d_term
float64 i_max
float64 i_min
float64 output
`,
		"control_msgs/PidState",
		"b138ec00e886c10e73f27e8712252ea6",
	}
)

type PidState struct {
	Header   std_msgs.Header
	Timestep ros.Duration
	Error    float64
	ErrorDot float64
	PError   float64
	IError   float64
	DError   float64
	PTerm    float64
	ITerm    float64
	DTerm    float64
	IMax     float64
	IMin     float64
	Output   float64
}

func (m *PidState) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "duration", &m.Timestep); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.Error); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.ErrorDot); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.PError); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.IError); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.DError); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.PTerm); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.ITerm); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.DTerm); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.IMax); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.IMin); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.Output); err != nil {
		return err
	}

	return
}

func (m *PidState) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// Timestep
	if err = ros.DeserializeMessageField(r, "duration", &m.Timestep); err != nil {
		return err
	}

	// Error
	if err = ros.DeserializeMessageField(r, "float64", &m.Error); err != nil {
		return err
	}

	// ErrorDot
	if err = ros.DeserializeMessageField(r, "float64", &m.ErrorDot); err != nil {
		return err
	}

	// PError
	if err = ros.DeserializeMessageField(r, "float64", &m.PError); err != nil {
		return err
	}

	// IError
	if err = ros.DeserializeMessageField(r, "float64", &m.IError); err != nil {
		return err
	}

	// DError
	if err = ros.DeserializeMessageField(r, "float64", &m.DError); err != nil {
		return err
	}

	// PTerm
	if err = ros.DeserializeMessageField(r, "float64", &m.PTerm); err != nil {
		return err
	}

	// ITerm
	if err = ros.DeserializeMessageField(r, "float64", &m.ITerm); err != nil {
		return err
	}

	// DTerm
	if err = ros.DeserializeMessageField(r, "float64", &m.DTerm); err != nil {
		return err
	}

	// IMax
	if err = ros.DeserializeMessageField(r, "float64", &m.IMax); err != nil {
		return err
	}

	// IMin
	if err = ros.DeserializeMessageField(r, "float64", &m.IMin); err != nil {
		return err
	}

	// Output
	if err = ros.DeserializeMessageField(r, "float64", &m.Output); err != nil {
		return err
	}

	return
}
