// Code generated by ros-gen-go.
// source: SingleJointPositionActionGoal.msg
// DO NOT EDIT!
package control_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/actionlib_msgs"
	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgSingleJointPositionActionGoal struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgSingleJointPositionActionGoal) Text() string {
	return t.text
}

func (t *_MsgSingleJointPositionActionGoal) Name() string {
	return t.name
}

func (t *_MsgSingleJointPositionActionGoal) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgSingleJointPositionActionGoal) NewMessage() ros.Message {
	m := new(SingleJointPositionActionGoal)

	return m
}

var (
	MsgSingleJointPositionActionGoal = &_MsgSingleJointPositionActionGoal{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
SingleJointPositionGoal goal
`,
		"control_msgs/SingleJointPositionActionGoal",
		"4b0d3d091471663e17749c1d0db90f61",
	}
)

type SingleJointPositionActionGoal struct {
	Header std_msgs.Header
	GoalId actionlib_msgs.GoalID
	Goal   SingleJointPositionGoal
}

func (m *SingleJointPositionActionGoal) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "actionlib_msgs/GoalID", &m.GoalId); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "SingleJointPositionGoal", &m.Goal); err != nil {
		return err
	}

	return
}

func (m *SingleJointPositionActionGoal) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "Header", &m.Header); err != nil {
		return err
	}

	// GoalId
	if err = ros.DeserializeMessageField(r, "actionlib_msgs/GoalID", &m.GoalId); err != nil {
		return err
	}

	// Goal
	if err = ros.DeserializeMessageField(r, "SingleJointPositionGoal", &m.Goal); err != nil {
		return err
	}

	return
}
