// Code generated by ros-gen-go.
// source: FileRemove.srv
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

// Service type metadata
type _SrvFileRemove struct {
	name    string
	md5sum  string
	text    string
	reqType ros.MessageType
	resType ros.MessageType
}

func (t *_SrvFileRemove) Name() string                  { return t.name }
func (t *_SrvFileRemove) MD5Sum() string                { return t.md5sum }
func (t *_SrvFileRemove) Text() string                  { return t.text }
func (t *_SrvFileRemove) RequestType() ros.MessageType  { return t.reqType }
func (t *_SrvFileRemove) ResponseType() ros.MessageType { return t.resType }
func (t *_SrvFileRemove) NewService() ros.Service {
	return new(FileRemove)
}

var (
	SrvFileRemove = &_SrvFileRemove{
		"mavros_msgs/FileRemove",
		"1c309002d7f7c6df7d3f094925ea8e10",
		`# FTP::Remove
#
# :success:	indicates success end of request
# :r_errno:	remote errno if applicapable

string file_path
---
bool success
int32 r_errno
`,
		MsgFileRemoveRequest,
		MsgFileRemoveResponse,
	}
)

type FileRemove struct {
	Request  FileRemoveRequest
	Response FileRemoveResponse
}

func (s *FileRemove) ReqMessage() ros.Message { return &s.Request }
func (s *FileRemove) ResMessage() ros.Message { return &s.Response }

// FileRemoveRequest

type _MsgFileRemoveRequest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFileRemoveRequest) Text() string {
	return t.text
}

func (t *_MsgFileRemoveRequest) Name() string {
	return t.name
}

func (t *_MsgFileRemoveRequest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFileRemoveRequest) NewMessage() ros.Message {
	m := new(FileRemoveRequest)

	return m
}

var (
	MsgFileRemoveRequest = &_MsgFileRemoveRequest{
		`# FTP::Remove
#
# :success:	indicates success end of request
# :r_errno:	remote errno if applicapable

string file_path
`,
		"mavros_msgs/FileRemoveRequest",
		"",
	}
)

type FileRemoveRequest struct {
	FilePath string
}

func (m *FileRemoveRequest) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "string", &m.FilePath); err != nil {
		return err
	}

	return
}

func (m *FileRemoveRequest) Deserialize(r io.Reader) (err error) {
	// FilePath
	if err = ros.DeserializeMessageField(r, "string", &m.FilePath); err != nil {
		return err
	}

	return
}

// FileRemoveResponse

type _MsgFileRemoveResponse struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFileRemoveResponse) Text() string {
	return t.text
}

func (t *_MsgFileRemoveResponse) Name() string {
	return t.name
}

func (t *_MsgFileRemoveResponse) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFileRemoveResponse) NewMessage() ros.Message {
	m := new(FileRemoveResponse)

	return m
}

var (
	MsgFileRemoveResponse = &_MsgFileRemoveResponse{
		`
bool success
int32 r_errno
`,
		"mavros_msgs/FileRemoveResponse",
		"",
	}
)

type FileRemoveResponse struct {
	Success bool
	RErrno  int32
}

func (m *FileRemoveResponse) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.Success); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "int32", &m.RErrno); err != nil {
		return err
	}

	return
}

func (m *FileRemoveResponse) Deserialize(r io.Reader) (err error) {
	// Success
	if err = ros.DeserializeMessageField(r, "bool", &m.Success); err != nil {
		return err
	}

	// RErrno
	if err = ros.DeserializeMessageField(r, "int32", &m.RErrno); err != nil {
		return err
	}

	return
}
