// Code generated by ros-gen-go.
// source: FileRename.srv
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

// Service type metadata
type _SrvFileRename struct {
	name    string
	md5sum  string
	text    string
	reqType ros.MessageType
	resType ros.MessageType
}

func (t *_SrvFileRename) Name() string                  { return t.name }
func (t *_SrvFileRename) MD5Sum() string                { return t.md5sum }
func (t *_SrvFileRename) Text() string                  { return t.text }
func (t *_SrvFileRename) RequestType() ros.MessageType  { return t.reqType }
func (t *_SrvFileRename) ResponseType() ros.MessageType { return t.resType }
func (t *_SrvFileRename) NewService() ros.Service {
	return new(FileRename)
}

var (
	SrvFileRename = &_SrvFileRename{
		"mavros_msgs/FileRename",
		"07d853e3d48c88a648998515aab1f5b7",
		`# FTP::Rename
#
# :success:	indicates success end of request
# :r_errno:	remote errno if applicapable

string old_path
string new_path
---
bool success
int32 r_errno
`,
		MsgFileRenameRequest,
		MsgFileRenameResponse,
	}
)

type FileRename struct {
	Request  FileRenameRequest
	Response FileRenameResponse
}

func (s *FileRename) ReqMessage() ros.Message { return &s.Request }
func (s *FileRename) ResMessage() ros.Message { return &s.Response }

// FileRenameRequest

type _MsgFileRenameRequest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFileRenameRequest) Text() string {
	return t.text
}

func (t *_MsgFileRenameRequest) Name() string {
	return t.name
}

func (t *_MsgFileRenameRequest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFileRenameRequest) NewMessage() ros.Message {
	m := new(FileRenameRequest)

	return m
}

var (
	MsgFileRenameRequest = &_MsgFileRenameRequest{
		`# FTP::Rename
#
# :success:	indicates success end of request
# :r_errno:	remote errno if applicapable

string old_path
string new_path
`,
		"mavros_msgs/FileRenameRequest",
		"",
	}
)

type FileRenameRequest struct {
	OldPath string
	NewPath string
}

func (m *FileRenameRequest) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "string", &m.OldPath); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "string", &m.NewPath); err != nil {
		return err
	}

	return
}

func (m *FileRenameRequest) Deserialize(r io.Reader) (err error) {
	// OldPath
	if err = ros.DeserializeMessageField(r, "string", &m.OldPath); err != nil {
		return err
	}

	// NewPath
	if err = ros.DeserializeMessageField(r, "string", &m.NewPath); err != nil {
		return err
	}

	return
}

// FileRenameResponse

type _MsgFileRenameResponse struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFileRenameResponse) Text() string {
	return t.text
}

func (t *_MsgFileRenameResponse) Name() string {
	return t.name
}

func (t *_MsgFileRenameResponse) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFileRenameResponse) NewMessage() ros.Message {
	m := new(FileRenameResponse)

	return m
}

var (
	MsgFileRenameResponse = &_MsgFileRenameResponse{
		`
bool success
int32 r_errno
`,
		"mavros_msgs/FileRenameResponse",
		"",
	}
)

type FileRenameResponse struct {
	Success bool
	RErrno  int32
}

func (m *FileRenameResponse) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.Success); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "int32", &m.RErrno); err != nil {
		return err
	}

	return
}

func (m *FileRenameResponse) Deserialize(r io.Reader) (err error) {
	// Success
	if err = ros.DeserializeMessageField(r, "bool", &m.Success); err != nil {
		return err
	}

	// RErrno
	if err = ros.DeserializeMessageField(r, "int32", &m.RErrno); err != nil {
		return err
	}

	return
}
