// Code generated by ros-gen-go.
// source: ParamGet.srv
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

// Service type metadata
type _SrvParamGet struct {
	name    string
	md5sum  string
	text    string
	reqType ros.MessageType
	resType ros.MessageType
}

func (t *_SrvParamGet) Name() string                  { return t.name }
func (t *_SrvParamGet) MD5Sum() string                { return t.md5sum }
func (t *_SrvParamGet) Text() string                  { return t.text }
func (t *_SrvParamGet) RequestType() ros.MessageType  { return t.reqType }
func (t *_SrvParamGet) ResponseType() ros.MessageType { return t.resType }
func (t *_SrvParamGet) NewService() ros.Service {
	return new(ParamGet)
}

var (
	SrvParamGet = &_SrvParamGet{
		"mavros_msgs/ParamGet",
		"777d24d2a7ab1765ef009a69f464d2bc",
		`# Request parameter from attached device

string param_id
---
bool success
ParamValue value
`,
		MsgParamGetRequest,
		MsgParamGetResponse,
	}
)

type ParamGet struct {
	Request  ParamGetRequest
	Response ParamGetResponse
}

func (s *ParamGet) ReqMessage() ros.Message { return &s.Request }
func (s *ParamGet) ResMessage() ros.Message { return &s.Response }

// ParamGetRequest

type _MsgParamGetRequest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgParamGetRequest) Text() string {
	return t.text
}

func (t *_MsgParamGetRequest) Name() string {
	return t.name
}

func (t *_MsgParamGetRequest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgParamGetRequest) NewMessage() ros.Message {
	m := new(ParamGetRequest)

	return m
}

var (
	MsgParamGetRequest = &_MsgParamGetRequest{
		`# Request parameter from attached device

string param_id
`,
		"mavros_msgs/ParamGetRequest",
		"",
	}
)

type ParamGetRequest struct {
	ParamId string
}

func (m *ParamGetRequest) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "string", &m.ParamId); err != nil {
		return err
	}

	return
}

func (m *ParamGetRequest) Deserialize(r io.Reader) (err error) {
	// ParamId
	if err = ros.DeserializeMessageField(r, "string", &m.ParamId); err != nil {
		return err
	}

	return
}

// ParamGetResponse

type _MsgParamGetResponse struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgParamGetResponse) Text() string {
	return t.text
}

func (t *_MsgParamGetResponse) Name() string {
	return t.name
}

func (t *_MsgParamGetResponse) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgParamGetResponse) NewMessage() ros.Message {
	m := new(ParamGetResponse)

	return m
}

var (
	MsgParamGetResponse = &_MsgParamGetResponse{
		`
bool success
ParamValue value
`,
		"mavros_msgs/ParamGetResponse",
		"",
	}
)

type ParamGetResponse struct {
	Success bool
	Value   ParamValue
}

func (m *ParamGetResponse) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.Success); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "ParamValue", &m.Value); err != nil {
		return err
	}

	return
}

func (m *ParamGetResponse) Deserialize(r io.Reader) (err error) {
	// Success
	if err = ros.DeserializeMessageField(r, "bool", &m.Success); err != nil {
		return err
	}

	// Value
	if err = ros.DeserializeMessageField(r, "ParamValue", &m.Value); err != nil {
		return err
	}

	return
}
