// Code generated by ros-gen-go.
// source: CommandLong.srv
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

// Service type metadata
type _SrvCommandLong struct {
	name    string
	md5sum  string
	text    string
	reqType ros.MessageType
	resType ros.MessageType
}

func (t *_SrvCommandLong) Name() string                  { return t.name }
func (t *_SrvCommandLong) MD5Sum() string                { return t.md5sum }
func (t *_SrvCommandLong) Text() string                  { return t.text }
func (t *_SrvCommandLong) RequestType() ros.MessageType  { return t.reqType }
func (t *_SrvCommandLong) ResponseType() ros.MessageType { return t.resType }
func (t *_SrvCommandLong) NewService() ros.Service {
	return new(CommandLong)
}

var (
	SrvCommandLong = &_SrvCommandLong{
		"mavros_msgs/CommandLong",
		"eb9034afc87577c0a235d45b8f3437d2",
		`# Generic COMMAND_LONG

bool broadcast # send this command in broadcast mode

uint16 command
uint8 confirmation
float32 param1
float32 param2
float32 param3
float32 param4
float32 param5	# x_lat
float32 param6	# y_lon
float32 param7	# z_alt
---
bool success
# raw result returned by COMMAND_ACK
uint8 result
`,
		MsgCommandLongRequest,
		MsgCommandLongResponse,
	}
)

type CommandLong struct {
	Request  CommandLongRequest
	Response CommandLongResponse
}

func (s *CommandLong) ReqMessage() ros.Message { return &s.Request }
func (s *CommandLong) ResMessage() ros.Message { return &s.Response }

// CommandLongRequest

type _MsgCommandLongRequest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgCommandLongRequest) Text() string {
	return t.text
}

func (t *_MsgCommandLongRequest) Name() string {
	return t.name
}

func (t *_MsgCommandLongRequest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgCommandLongRequest) NewMessage() ros.Message {
	m := new(CommandLongRequest)

	return m
}

var (
	MsgCommandLongRequest = &_MsgCommandLongRequest{
		`# Generic COMMAND_LONG

bool broadcast # send this command in broadcast mode

uint16 command
uint8 confirmation
float32 param1
float32 param2
float32 param3
float32 param4
float32 param5	# x_lat
float32 param6	# y_lon
float32 param7	# z_alt
`,
		"mavros_msgs/CommandLongRequest",
		"",
	}
)

type CommandLongRequest struct {
	Broadcast    bool
	Command      uint16
	Confirmation uint8
	Param1       float32
	Param2       float32
	Param3       float32
	Param4       float32
	Param5       float32
	Param6       float32
	Param7       float32
}

func (m *CommandLongRequest) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.Broadcast); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint16", &m.Command); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint8", &m.Confirmation); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Param1); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Param2); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Param3); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Param4); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Param5); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Param6); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Param7); err != nil {
		return err
	}

	return
}

func (m *CommandLongRequest) Deserialize(r io.Reader) (err error) {
	// Broadcast
	if err = ros.DeserializeMessageField(r, "bool", &m.Broadcast); err != nil {
		return err
	}

	// Command
	if err = ros.DeserializeMessageField(r, "uint16", &m.Command); err != nil {
		return err
	}

	// Confirmation
	if err = ros.DeserializeMessageField(r, "uint8", &m.Confirmation); err != nil {
		return err
	}

	// Param1
	if err = ros.DeserializeMessageField(r, "float32", &m.Param1); err != nil {
		return err
	}

	// Param2
	if err = ros.DeserializeMessageField(r, "float32", &m.Param2); err != nil {
		return err
	}

	// Param3
	if err = ros.DeserializeMessageField(r, "float32", &m.Param3); err != nil {
		return err
	}

	// Param4
	if err = ros.DeserializeMessageField(r, "float32", &m.Param4); err != nil {
		return err
	}

	// Param5
	if err = ros.DeserializeMessageField(r, "float32", &m.Param5); err != nil {
		return err
	}

	// Param6
	if err = ros.DeserializeMessageField(r, "float32", &m.Param6); err != nil {
		return err
	}

	// Param7
	if err = ros.DeserializeMessageField(r, "float32", &m.Param7); err != nil {
		return err
	}

	return
}

// CommandLongResponse

type _MsgCommandLongResponse struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgCommandLongResponse) Text() string {
	return t.text
}

func (t *_MsgCommandLongResponse) Name() string {
	return t.name
}

func (t *_MsgCommandLongResponse) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgCommandLongResponse) NewMessage() ros.Message {
	m := new(CommandLongResponse)

	return m
}

var (
	MsgCommandLongResponse = &_MsgCommandLongResponse{
		`
bool success
# raw result returned by COMMAND_ACK
uint8 result
`,
		"mavros_msgs/CommandLongResponse",
		"",
	}
)

type CommandLongResponse struct {
	Success bool
	Result  uint8
}

func (m *CommandLongResponse) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.Success); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint8", &m.Result); err != nil {
		return err
	}

	return
}

func (m *CommandLongResponse) Deserialize(r io.Reader) (err error) {
	// Success
	if err = ros.DeserializeMessageField(r, "bool", &m.Success); err != nil {
		return err
	}

	// Result
	if err = ros.DeserializeMessageField(r, "uint8", &m.Result); err != nil {
		return err
	}

	return
}
