// Code generated by ros-gen-go.
// source: GetMapResult.msg
// DO NOT EDIT!
package nav_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

type _MsgGetMapResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGetMapResult) Text() string {
	return t.text
}

func (t *_MsgGetMapResult) Name() string {
	return t.name
}

func (t *_MsgGetMapResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGetMapResult) NewMessage() ros.Message {
	m := new(GetMapResult)

	return m
}

var (
	MsgGetMapResult = &_MsgGetMapResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
nav_msgs/OccupancyGrid map
`,
		"nav_msgs/GetMapResult",
		"6cdd0a18e0aff5b0a3ca2326a89b54ff",
	}
)

type GetMapResult struct {
	Map OccupancyGrid
}

func (m *GetMapResult) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "nav_msgs/OccupancyGrid", &m.Map); err != nil {
		return err
	}

	return
}

func (m *GetMapResult) Deserialize(r io.Reader) (err error) {
	// Map
	if err = ros.DeserializeMessageField(r, "nav_msgs/OccupancyGrid", &m.Map); err != nil {
		return err
	}

	return
}
