// Code generated by ros-gen-go.
// source: Altitude.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgAltitude struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgAltitude) Text() string {
	return t.text
}

func (t *_MsgAltitude) Name() string {
	return t.name
}

func (t *_MsgAltitude) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgAltitude) NewMessage() ros.Message {
	m := new(Altitude)

	return m
}

var (
	MsgAltitude = &_MsgAltitude{
		`# Altitude information
#
# https://mavlink.io/en/messages/common.html#ALTITUDE

std_msgs/Header header

float32 monotonic
float32 amsl
float32 local
float32 relative
float32 terrain
float32 bottom_clearance
`,
		"mavros_msgs/Altitude",
		"1296a05dc5b6160be0ae04ba9ed3a3fa",
	}
)

type Altitude struct {
	Header          std_msgs.Header
	Monotonic       float32
	Amsl            float32
	Local           float32
	Relative        float32
	Terrain         float32
	BottomClearance float32
}

func (m *Altitude) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Monotonic); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Amsl); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Local); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Relative); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Terrain); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.BottomClearance); err != nil {
		return err
	}

	return
}

func (m *Altitude) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// Monotonic
	if err = ros.DeserializeMessageField(r, "float32", &m.Monotonic); err != nil {
		return err
	}

	// Amsl
	if err = ros.DeserializeMessageField(r, "float32", &m.Amsl); err != nil {
		return err
	}

	// Local
	if err = ros.DeserializeMessageField(r, "float32", &m.Local); err != nil {
		return err
	}

	// Relative
	if err = ros.DeserializeMessageField(r, "float32", &m.Relative); err != nil {
		return err
	}

	// Terrain
	if err = ros.DeserializeMessageField(r, "float32", &m.Terrain); err != nil {
		return err
	}

	// BottomClearance
	if err = ros.DeserializeMessageField(r, "float32", &m.BottomClearance); err != nil {
		return err
	}

	return
}
