// Code generated by ros-gen-go.
// source: BatteryStatus.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgBatteryStatus struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgBatteryStatus) Text() string {
	return t.text
}

func (t *_MsgBatteryStatus) Name() string {
	return t.name
}

func (t *_MsgBatteryStatus) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgBatteryStatus) NewMessage() ros.Message {
	m := new(BatteryStatus)

	return m
}

var (
	MsgBatteryStatus = &_MsgBatteryStatus{
		`# Represent battery status from SYSTEM_STATUS
#
# To be replaced when sensor_msgs/BatteryState PR will be merged
# https://github.com/ros/common_msgs/pull/74

std_msgs/Header header
float32 voltage # [V]
float32 current # [A]
float32 remaining # 0..1
`,
		"mavros_msgs/BatteryStatus",
		"8ba4ae7c602c5ae6a7e8f3ffb652dc5f",
	}
)

type BatteryStatus struct {
	Header    std_msgs.Header
	Voltage   float32
	Current   float32
	Remaining float32
}

func (m *BatteryStatus) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Voltage); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Current); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Remaining); err != nil {
		return err
	}

	return
}

func (m *BatteryStatus) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// Voltage
	if err = ros.DeserializeMessageField(r, "float32", &m.Voltage); err != nil {
		return err
	}

	// Current
	if err = ros.DeserializeMessageField(r, "float32", &m.Current); err != nil {
		return err
	}

	// Remaining
	if err = ros.DeserializeMessageField(r, "float32", &m.Remaining); err != nil {
		return err
	}

	return
}
