// Code generated by ros-gen-go.
// source: CamIMUStamp.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

type _MsgCamIMUStamp struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgCamIMUStamp) Text() string {
	return t.text
}

func (t *_MsgCamIMUStamp) Name() string {
	return t.name
}

func (t *_MsgCamIMUStamp) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgCamIMUStamp) NewMessage() ros.Message {
	m := new(CamIMUStamp)

	return m
}

var (
	MsgCamIMUStamp = &_MsgCamIMUStamp{
		`# IMU-Camera synchronisation data

time frame_stamp		# Timestamp when the camera was triggered
int32 frame_seq_id		# Sequence number of the image frame
`,
		"mavros_msgs/CamIMUStamp",
		"ac22af9031671dd528a56f12d0986660",
	}
)

type CamIMUStamp struct {
	FrameStamp ros.Time
	FrameSeqId int32
}

func (m *CamIMUStamp) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "time", &m.FrameStamp); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "int32", &m.FrameSeqId); err != nil {
		return err
	}

	return
}

func (m *CamIMUStamp) Deserialize(r io.Reader) (err error) {
	// FrameStamp
	if err = ros.DeserializeMessageField(r, "time", &m.FrameStamp); err != nil {
		return err
	}

	// FrameSeqId
	if err = ros.DeserializeMessageField(r, "int32", &m.FrameSeqId); err != nil {
		return err
	}

	return
}
