// Code generated by ros-gen-go.
// source: CommandTriggerControl.srv
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

// Service type metadata
type _SrvCommandTriggerControl struct {
	name    string
	md5sum  string
	text    string
	reqType ros.MessageType
	resType ros.MessageType
}

func (t *_SrvCommandTriggerControl) Name() string                  { return t.name }
func (t *_SrvCommandTriggerControl) MD5Sum() string                { return t.md5sum }
func (t *_SrvCommandTriggerControl) Text() string                  { return t.text }
func (t *_SrvCommandTriggerControl) RequestType() ros.MessageType  { return t.reqType }
func (t *_SrvCommandTriggerControl) ResponseType() ros.MessageType { return t.resType }
func (t *_SrvCommandTriggerControl) NewService() ros.Service {
	return new(CommandTriggerControl)
}

var (
	SrvCommandTriggerControl = &_SrvCommandTriggerControl{
		"mavros_msgs/CommandTriggerControl",
		"65be46a6918cb61b7dceb7c9ba9b1c97",
		`# Type for controlling onboard camera triggering system

bool    trigger_enable		# Trigger enable/disable
bool    sequence_reset		# Reset the trigger sequence
bool    trigger_pause		# Pause triggering, but without switching the camera off or retracting it.
---
bool success
uint8 result
`,
		MsgCommandTriggerControlRequest,
		MsgCommandTriggerControlResponse,
	}
)

type CommandTriggerControl struct {
	Request  CommandTriggerControlRequest
	Response CommandTriggerControlResponse
}

func (s *CommandTriggerControl) ReqMessage() ros.Message { return &s.Request }
func (s *CommandTriggerControl) ResMessage() ros.Message { return &s.Response }

// CommandTriggerControlRequest

type _MsgCommandTriggerControlRequest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgCommandTriggerControlRequest) Text() string {
	return t.text
}

func (t *_MsgCommandTriggerControlRequest) Name() string {
	return t.name
}

func (t *_MsgCommandTriggerControlRequest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgCommandTriggerControlRequest) NewMessage() ros.Message {
	m := new(CommandTriggerControlRequest)

	return m
}

var (
	MsgCommandTriggerControlRequest = &_MsgCommandTriggerControlRequest{
		`# Type for controlling onboard camera triggering system

bool    trigger_enable		# Trigger enable/disable
bool    sequence_reset		# Reset the trigger sequence
bool    trigger_pause		# Pause triggering, but without switching the camera off or retracting it.
`,
		"mavros_msgs/CommandTriggerControlRequest",
		"",
	}
)

type CommandTriggerControlRequest struct {
	TriggerEnable bool
	SequenceReset bool
	TriggerPause  bool
}

func (m *CommandTriggerControlRequest) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.TriggerEnable); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "bool", &m.SequenceReset); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "bool", &m.TriggerPause); err != nil {
		return err
	}

	return
}

func (m *CommandTriggerControlRequest) Deserialize(r io.Reader) (err error) {
	// TriggerEnable
	if err = ros.DeserializeMessageField(r, "bool", &m.TriggerEnable); err != nil {
		return err
	}

	// SequenceReset
	if err = ros.DeserializeMessageField(r, "bool", &m.SequenceReset); err != nil {
		return err
	}

	// TriggerPause
	if err = ros.DeserializeMessageField(r, "bool", &m.TriggerPause); err != nil {
		return err
	}

	return
}

// CommandTriggerControlResponse

type _MsgCommandTriggerControlResponse struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgCommandTriggerControlResponse) Text() string {
	return t.text
}

func (t *_MsgCommandTriggerControlResponse) Name() string {
	return t.name
}

func (t *_MsgCommandTriggerControlResponse) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgCommandTriggerControlResponse) NewMessage() ros.Message {
	m := new(CommandTriggerControlResponse)

	return m
}

var (
	MsgCommandTriggerControlResponse = &_MsgCommandTriggerControlResponse{
		`
bool success
uint8 result
`,
		"mavros_msgs/CommandTriggerControlResponse",
		"",
	}
)

type CommandTriggerControlResponse struct {
	Success bool
	Result  uint8
}

func (m *CommandTriggerControlResponse) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.Success); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint8", &m.Result); err != nil {
		return err
	}

	return
}

func (m *CommandTriggerControlResponse) Deserialize(r io.Reader) (err error) {
	// Success
	if err = ros.DeserializeMessageField(r, "bool", &m.Success); err != nil {
		return err
	}

	// Result
	if err = ros.DeserializeMessageField(r, "uint8", &m.Result); err != nil {
		return err
	}

	return
}
