// Code generated by ros-gen-go.
// source: CommandCode.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

const (
	CommandCode_CMD_DO_SET_MODE                    uint16 = 176
	CommandCode_CMD_DO_JUMP                        uint16 = 177
	CommandCode_CMD_DO_CHANGE_SPEED                uint16 = 178
	CommandCode_CMD_DO_SET_HOME                    uint16 = 179
	CommandCode_CMD_DO_SET_RELAY                   uint16 = 181
	CommandCode_CMD_DO_REPEAT_RELAY                uint16 = 182
	CommandCode_CMD_DO_SET_SERVO                   uint16 = 183
	CommandCode_CMD_DO_REPEAT_SERVO                uint16 = 184
	CommandCode_CMD_DO_CONTROL_VIDEO               uint16 = 200
	CommandCode_CMD_DO_SET_ROI                     uint16 = 201
	CommandCode_CMD_DO_MOUNT_CONTROL               uint16 = 205
	CommandCode_CMD_DO_SET_CAM_TRIGG_DIST          uint16 = 206
	CommandCode_CMD_DO_FENCE_ENABLE                uint16 = 207
	CommandCode_CMD_DO_PARACHUTE                   uint16 = 208
	CommandCode_CMD_DO_INVERTED_FLIGHT             uint16 = 210
	CommandCode_CMD_DO_MOUNT_CONTROL_QUAT          uint16 = 220
	CommandCode_CMD_PREFLIGHT_CALIBRATION          uint16 = 241
	CommandCode_CMD_MISSION_START                  uint16 = 300
	CommandCode_CMD_COMPONENT_ARM_DISARM           uint16 = 400
	CommandCode_CMD_GET_HOME_POSITION              uint16 = 410
	CommandCode_CMD_START_RX_PAIR                  uint16 = 500
	CommandCode_CMD_REQUEST_AUTOPILOT_CAPABILITIES uint16 = 520
	CommandCode_CMD_DO_TRIGGER_CONTROL             uint16 = 2003
	CommandCode_NAV_WAYPOINT                       uint16 = 16
	CommandCode_NAV_LOITER_UNLIM                   uint16 = 17
	CommandCode_NAV_LOITER_TURNS                   uint16 = 18
	CommandCode_NAV_LOITER_TIME                    uint16 = 19
	CommandCode_NAV_RETURN_TO_LAUNCH               uint16 = 20
	CommandCode_NAV_LAND                           uint16 = 21
	CommandCode_NAV_TAKEOFF                        uint16 = 22
)

type _MsgCommandCode struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgCommandCode) Text() string {
	return t.text
}

func (t *_MsgCommandCode) Name() string {
	return t.name
}

func (t *_MsgCommandCode) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgCommandCode) NewMessage() ros.Message {
	m := new(CommandCode)

	return m
}

var (
	MsgCommandCode = &_MsgCommandCode{
		`# Some MAV_CMD command codes.
# Actual meaning and params you may find in MAVLink documentation
# http://mavlink.org/messages/common#ENUM_MAV_CMD

# some common MAV_CMD
uint16 CMD_DO_SET_MODE = 176
uint16 CMD_DO_JUMP = 177
uint16 CMD_DO_CHANGE_SPEED = 178
uint16 CMD_DO_SET_HOME = 179
uint16 CMD_DO_SET_RELAY = 181
uint16 CMD_DO_REPEAT_RELAY = 182
uint16 CMD_DO_SET_SERVO = 183
uint16 CMD_DO_REPEAT_SERVO = 184
uint16 CMD_DO_CONTROL_VIDEO = 200
uint16 CMD_DO_SET_ROI = 201
uint16 CMD_DO_MOUNT_CONTROL = 205
uint16 CMD_DO_SET_CAM_TRIGG_DIST = 206
uint16 CMD_DO_FENCE_ENABLE = 207
uint16 CMD_DO_PARACHUTE = 208
uint16 CMD_DO_INVERTED_FLIGHT = 210
uint16 CMD_DO_MOUNT_CONTROL_QUAT = 220
uint16 CMD_PREFLIGHT_CALIBRATION = 241
uint16 CMD_MISSION_START = 300
uint16 CMD_COMPONENT_ARM_DISARM = 400
uint16 CMD_GET_HOME_POSITION = 410
uint16 CMD_START_RX_PAIR = 500
uint16 CMD_REQUEST_AUTOPILOT_CAPABILITIES = 520
uint16 CMD_DO_TRIGGER_CONTROL = 2003

# Waypoint related commands
uint16 NAV_WAYPOINT = 16
uint16 NAV_LOITER_UNLIM = 17
uint16 NAV_LOITER_TURNS = 18
uint16 NAV_LOITER_TIME = 19
uint16 NAV_RETURN_TO_LAUNCH = 20
uint16 NAV_LAND = 21
uint16 NAV_TAKEOFF = 22
`,
		"mavros_msgs/CommandCode",
		"5f2b024f460e58b487bc6e944e943789",
	}
)

type CommandCode struct {
}

func (m *CommandCode) Serialize(w io.Writer) (err error) {
	return
}

func (m *CommandCode) Deserialize(r io.Reader) (err error) {
	return
}
