// Code generated by ros-gen-go.
// source: CompanionProcessStatus.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

const (
	CompanionProcessStatus_MAV_STATE_UNINIT                     uint8 = 0
	CompanionProcessStatus_MAV_STATE_BOOT                       uint8 = 1
	CompanionProcessStatus_MAV_STATE_CALIBRATING                uint8 = 2
	CompanionProcessStatus_MAV_STATE_STANDBY                    uint8 = 3
	CompanionProcessStatus_MAV_STATE_ACTIVE                     uint8 = 4
	CompanionProcessStatus_MAV_STATE_CRITICAL                   uint8 = 5
	CompanionProcessStatus_MAV_STATE_EMERGENCY                  uint8 = 6
	CompanionProcessStatus_MAV_STATE_POWEROFF                   uint8 = 7
	CompanionProcessStatus_MAV_STATE_FLIGHT_TERMINATION         uint8 = 8
	CompanionProcessStatus_MAV_COMP_ID_OBSTACLE_AVOIDANCE       uint8 = 196
	CompanionProcessStatus_MAV_COMP_ID_VISUAL_INERTIAL_ODOMETRY uint8 = 197
)

type _MsgCompanionProcessStatus struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgCompanionProcessStatus) Text() string {
	return t.text
}

func (t *_MsgCompanionProcessStatus) Name() string {
	return t.name
}

func (t *_MsgCompanionProcessStatus) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgCompanionProcessStatus) NewMessage() ros.Message {
	m := new(CompanionProcessStatus)

	return m
}

var (
	MsgCompanionProcessStatus = &_MsgCompanionProcessStatus{
		`# Mavros message: COMPANIONPROCESSSTATUS

std_msgs/Header header

uint8 state			# See enum COMPANION_PROCESS_STATE
uint8 component		# See enum MAV_COMPONENT

uint8 MAV_STATE_UNINIT = 0
uint8 MAV_STATE_BOOT = 1
uint8 MAV_STATE_CALIBRATING = 2
uint8 MAV_STATE_STANDBY = 3
uint8 MAV_STATE_ACTIVE = 4
uint8 MAV_STATE_CRITICAL = 5
uint8 MAV_STATE_EMERGENCY = 6
uint8 MAV_STATE_POWEROFF = 7
uint8 MAV_STATE_FLIGHT_TERMINATION = 8

uint8 MAV_COMP_ID_OBSTACLE_AVOIDANCE = 196
uint8 MAV_COMP_ID_VISUAL_INERTIAL_ODOMETRY = 197
`,
		"mavros_msgs/CompanionProcessStatus",
		"b6dd787fcd873e87778987b1845f4cb5",
	}
)

type CompanionProcessStatus struct {
	Header    std_msgs.Header
	State     uint8
	Component uint8
}

func (m *CompanionProcessStatus) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint8", &m.State); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint8", &m.Component); err != nil {
		return err
	}

	return
}

func (m *CompanionProcessStatus) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// State
	if err = ros.DeserializeMessageField(r, "uint8", &m.State); err != nil {
		return err
	}

	// Component
	if err = ros.DeserializeMessageField(r, "uint8", &m.Component); err != nil {
		return err
	}

	return
}
