// Code generated by ros-gen-go.
// source: ExtendedState.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgExtendedState struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgExtendedState) Text() string {
	return t.text
}

func (t *_MsgExtendedState) Name() string {
	return t.name
}

func (t *_MsgExtendedState) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgExtendedState) NewMessage() ros.Message {
	m := new(ExtendedState)

	return m
}

var (
	MsgExtendedState = &_MsgExtendedState{
		`# Extended autopilot state
#
# http://mavlink.org/messages/common#EXTENDED_SYS_STATE

uint8 VTOL_STATE_UNDEFINED = 0
uint8 VTOL_STATE_TRANSITION_TO_FW = 1
uint8 VTOL_STATE_TRANSITION_TO_MC = 2
uint8 VTOL_STATE_MC = 3
uint8 VTOL_STATE_FW = 4

uint8 LANDED_STATE_UNDEFINED = 0
uint8 LANDED_STATE_ON_GROUND = 1
uint8 LANDED_STATE_IN_AIR = 2
uint8 LANDED_STATE_TAKEOFF = 3
uint8 LANDED_STATE_LANDING = 4

std_msgs/Header header
uint8 vtol_state
uint8 landed_state
`,
		"mavros_msgs/ExtendedState",
		"ae780b1800fe17b917369d21b90058bd",
	}
)

type ExtendedState struct {
	Header      std_msgs.Header
	VtolState   uint8
	LandedState uint8
}

func (m *ExtendedState) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint8", &m.VtolState); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint8", &m.LandedState); err != nil {
		return err
	}

	return
}

func (m *ExtendedState) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// VtolState
	if err = ros.DeserializeMessageField(r, "uint8", &m.VtolState); err != nil {
		return err
	}

	// LandedState
	if err = ros.DeserializeMessageField(r, "uint8", &m.LandedState); err != nil {
		return err
	}

	return
}
