// Code generated by ros-gen-go.
// source: FileRemoveDir.srv
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

// Service type metadata
type _SrvFileRemoveDir struct {
	name    string
	md5sum  string
	text    string
	reqType ros.MessageType
	resType ros.MessageType
}

func (t *_SrvFileRemoveDir) Name() string                  { return t.name }
func (t *_SrvFileRemoveDir) MD5Sum() string                { return t.md5sum }
func (t *_SrvFileRemoveDir) Text() string                  { return t.text }
func (t *_SrvFileRemoveDir) RequestType() ros.MessageType  { return t.reqType }
func (t *_SrvFileRemoveDir) ResponseType() ros.MessageType { return t.resType }
func (t *_SrvFileRemoveDir) NewService() ros.Service {
	return new(FileRemoveDir)
}

var (
	SrvFileRemoveDir = &_SrvFileRemoveDir{
		"mavros_msgs/FileRemoveDir",
		"f140c5ef05b00c3cfc30d5a2061b4d63",
		`# FTP::RemoveDir
#
# :success:	indicates success end of request
# :r_errno:	remote errno if applicapable

string dir_path
---
bool success
int32 r_errno
`,
		MsgFileRemoveDirRequest,
		MsgFileRemoveDirResponse,
	}
)

type FileRemoveDir struct {
	Request  FileRemoveDirRequest
	Response FileRemoveDirResponse
}

func (s *FileRemoveDir) ReqMessage() ros.Message { return &s.Request }
func (s *FileRemoveDir) ResMessage() ros.Message { return &s.Response }

// FileRemoveDirRequest

type _MsgFileRemoveDirRequest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFileRemoveDirRequest) Text() string {
	return t.text
}

func (t *_MsgFileRemoveDirRequest) Name() string {
	return t.name
}

func (t *_MsgFileRemoveDirRequest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFileRemoveDirRequest) NewMessage() ros.Message {
	m := new(FileRemoveDirRequest)

	return m
}

var (
	MsgFileRemoveDirRequest = &_MsgFileRemoveDirRequest{
		`# FTP::RemoveDir
#
# :success:	indicates success end of request
# :r_errno:	remote errno if applicapable

string dir_path
`,
		"mavros_msgs/FileRemoveDirRequest",
		"f140c5ef05b00c3cfc30d5a2061b4d63",
	}
)

type FileRemoveDirRequest struct {
	DirPath string
}

func (m *FileRemoveDirRequest) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "string", &m.DirPath); err != nil {
		return err
	}

	return
}

func (m *FileRemoveDirRequest) Deserialize(r io.Reader) (err error) {
	// DirPath
	if err = ros.DeserializeMessageField(r, "string", &m.DirPath); err != nil {
		return err
	}

	return
}

// FileRemoveDirResponse

type _MsgFileRemoveDirResponse struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFileRemoveDirResponse) Text() string {
	return t.text
}

func (t *_MsgFileRemoveDirResponse) Name() string {
	return t.name
}

func (t *_MsgFileRemoveDirResponse) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFileRemoveDirResponse) NewMessage() ros.Message {
	m := new(FileRemoveDirResponse)

	return m
}

var (
	MsgFileRemoveDirResponse = &_MsgFileRemoveDirResponse{
		`
bool success
int32 r_errno
`,
		"mavros_msgs/FileRemoveDirResponse",
		"f140c5ef05b00c3cfc30d5a2061b4d63",
	}
)

type FileRemoveDirResponse struct {
	Success bool
	RErrno  int32
}

func (m *FileRemoveDirResponse) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.Success); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "int32", &m.RErrno); err != nil {
		return err
	}

	return
}

func (m *FileRemoveDirResponse) Deserialize(r io.Reader) (err error) {
	// Success
	if err = ros.DeserializeMessageField(r, "bool", &m.Success); err != nil {
		return err
	}

	// RErrno
	if err = ros.DeserializeMessageField(r, "int32", &m.RErrno); err != nil {
		return err
	}

	return
}
