// Code generated by ros-gen-go.
// source: FileTruncate.srv
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

// Service type metadata
type _SrvFileTruncate struct {
	name    string
	md5sum  string
	text    string
	reqType ros.MessageType
	resType ros.MessageType
}

func (t *_SrvFileTruncate) Name() string                  { return t.name }
func (t *_SrvFileTruncate) MD5Sum() string                { return t.md5sum }
func (t *_SrvFileTruncate) Text() string                  { return t.text }
func (t *_SrvFileTruncate) RequestType() ros.MessageType  { return t.reqType }
func (t *_SrvFileTruncate) ResponseType() ros.MessageType { return t.resType }
func (t *_SrvFileTruncate) NewService() ros.Service {
	return new(FileTruncate)
}

var (
	SrvFileTruncate = &_SrvFileTruncate{
		"mavros_msgs/FileTruncate",
		"71bf45fe3600fc220a82346ce1d1430c",
		`# FTP::Truncate
#
# :success:	indicates success end of request
# :r_errno:	remote errno if applicapable

string file_path
uint64 length
---
bool success
int32 r_errno
`,
		MsgFileTruncateRequest,
		MsgFileTruncateResponse,
	}
)

type FileTruncate struct {
	Request  FileTruncateRequest
	Response FileTruncateResponse
}

func (s *FileTruncate) ReqMessage() ros.Message { return &s.Request }
func (s *FileTruncate) ResMessage() ros.Message { return &s.Response }

// FileTruncateRequest

type _MsgFileTruncateRequest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFileTruncateRequest) Text() string {
	return t.text
}

func (t *_MsgFileTruncateRequest) Name() string {
	return t.name
}

func (t *_MsgFileTruncateRequest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFileTruncateRequest) NewMessage() ros.Message {
	m := new(FileTruncateRequest)

	return m
}

var (
	MsgFileTruncateRequest = &_MsgFileTruncateRequest{
		`# FTP::Truncate
#
# :success:	indicates success end of request
# :r_errno:	remote errno if applicapable

string file_path
uint64 length
`,
		"mavros_msgs/FileTruncateRequest",
		"71bf45fe3600fc220a82346ce1d1430c",
	}
)

type FileTruncateRequest struct {
	FilePath string
	Length   uint64
}

func (m *FileTruncateRequest) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "string", &m.FilePath); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint64", &m.Length); err != nil {
		return err
	}

	return
}

func (m *FileTruncateRequest) Deserialize(r io.Reader) (err error) {
	// FilePath
	if err = ros.DeserializeMessageField(r, "string", &m.FilePath); err != nil {
		return err
	}

	// Length
	if err = ros.DeserializeMessageField(r, "uint64", &m.Length); err != nil {
		return err
	}

	return
}

// FileTruncateResponse

type _MsgFileTruncateResponse struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFileTruncateResponse) Text() string {
	return t.text
}

func (t *_MsgFileTruncateResponse) Name() string {
	return t.name
}

func (t *_MsgFileTruncateResponse) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFileTruncateResponse) NewMessage() ros.Message {
	m := new(FileTruncateResponse)

	return m
}

var (
	MsgFileTruncateResponse = &_MsgFileTruncateResponse{
		`
bool success
int32 r_errno
`,
		"mavros_msgs/FileTruncateResponse",
		"71bf45fe3600fc220a82346ce1d1430c",
	}
)

type FileTruncateResponse struct {
	Success bool
	RErrno  int32
}

func (m *FileTruncateResponse) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.Success); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "int32", &m.RErrno); err != nil {
		return err
	}

	return
}

func (m *FileTruncateResponse) Deserialize(r io.Reader) (err error) {
	// Success
	if err = ros.DeserializeMessageField(r, "bool", &m.Success); err != nil {
		return err
	}

	// RErrno
	if err = ros.DeserializeMessageField(r, "int32", &m.RErrno); err != nil {
		return err
	}

	return
}
