// Code generated by ros-gen-go.
// source: FileMakeDir.srv
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

// Service type metadata
type _SrvFileMakeDir struct {
	name    string
	md5sum  string
	text    string
	reqType ros.MessageType
	resType ros.MessageType
}

func (t *_SrvFileMakeDir) Name() string                  { return t.name }
func (t *_SrvFileMakeDir) MD5Sum() string                { return t.md5sum }
func (t *_SrvFileMakeDir) Text() string                  { return t.text }
func (t *_SrvFileMakeDir) RequestType() ros.MessageType  { return t.reqType }
func (t *_SrvFileMakeDir) ResponseType() ros.MessageType { return t.resType }
func (t *_SrvFileMakeDir) NewService() ros.Service {
	return new(FileMakeDir)
}

var (
	SrvFileMakeDir = &_SrvFileMakeDir{
		"mavros_msgs/FileMakeDir",
		"f140c5ef05b00c3cfc30d5a2061b4d63",
		`# FTP::MakeDir
#
# :success:	indicates success end of request
# :r_errno:	remote errno if applicapable

string dir_path
---
bool success
int32 r_errno
`,
		MsgFileMakeDirRequest,
		MsgFileMakeDirResponse,
	}
)

type FileMakeDir struct {
	Request  FileMakeDirRequest
	Response FileMakeDirResponse
}

func (s *FileMakeDir) ReqMessage() ros.Message { return &s.Request }
func (s *FileMakeDir) ResMessage() ros.Message { return &s.Response }

// FileMakeDirRequest

type _MsgFileMakeDirRequest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFileMakeDirRequest) Text() string {
	return t.text
}

func (t *_MsgFileMakeDirRequest) Name() string {
	return t.name
}

func (t *_MsgFileMakeDirRequest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFileMakeDirRequest) NewMessage() ros.Message {
	m := new(FileMakeDirRequest)

	return m
}

var (
	MsgFileMakeDirRequest = &_MsgFileMakeDirRequest{
		`# FTP::MakeDir
#
# :success:	indicates success end of request
# :r_errno:	remote errno if applicapable

string dir_path
`,
		"mavros_msgs/FileMakeDirRequest",
		"f140c5ef05b00c3cfc30d5a2061b4d63",
	}
)

type FileMakeDirRequest struct {
	DirPath string
}

func (m *FileMakeDirRequest) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "string", &m.DirPath); err != nil {
		return err
	}

	return
}

func (m *FileMakeDirRequest) Deserialize(r io.Reader) (err error) {
	// DirPath
	if err = ros.DeserializeMessageField(r, "string", &m.DirPath); err != nil {
		return err
	}

	return
}

// FileMakeDirResponse

type _MsgFileMakeDirResponse struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgFileMakeDirResponse) Text() string {
	return t.text
}

func (t *_MsgFileMakeDirResponse) Name() string {
	return t.name
}

func (t *_MsgFileMakeDirResponse) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgFileMakeDirResponse) NewMessage() ros.Message {
	m := new(FileMakeDirResponse)

	return m
}

var (
	MsgFileMakeDirResponse = &_MsgFileMakeDirResponse{
		`
bool success
int32 r_errno
`,
		"mavros_msgs/FileMakeDirResponse",
		"f140c5ef05b00c3cfc30d5a2061b4d63",
	}
)

type FileMakeDirResponse struct {
	Success bool
	RErrno  int32
}

func (m *FileMakeDirResponse) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.Success); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "int32", &m.RErrno); err != nil {
		return err
	}

	return
}

func (m *FileMakeDirResponse) Deserialize(r io.Reader) (err error) {
	// Success
	if err = ros.DeserializeMessageField(r, "bool", &m.Success); err != nil {
		return err
	}

	// RErrno
	if err = ros.DeserializeMessageField(r, "int32", &m.RErrno); err != nil {
		return err
	}

	return
}
