// Code generated by ros-gen-go.
// source: LogData.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"encoding/binary"
	"fmt"
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgLogData struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgLogData) Text() string {
	return t.text
}

func (t *_MsgLogData) Name() string {
	return t.name
}

func (t *_MsgLogData) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgLogData) NewMessage() ros.Message {
	m := new(LogData)

	return m
}

var (
	MsgLogData = &_MsgLogData{
		`# Reply to LogRequestData, - a chunk of a log
#
#  :id: - log id
#  :offset: - offset into the log
#  :data: - chunk of data (if zero-sized, then there are no more chunks)

std_msgs/Header header

uint16 id
uint32 offset
uint8[] data
`,
		"mavros_msgs/LogData",
		"ccaa27ba630f8f5d02c287763eb1e91b",
	}
)

type LogData struct {
	Header std_msgs.Header
	Id     uint16
	Offset uint32
	Data   []uint8
}

func (m *LogData) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint16", &m.Id); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint32", &m.Offset); err != nil {
		return err
	}

	// Write size little endian
	err = binary.Write(w, binary.LittleEndian, uint32(len(m.Data)))
	if err != nil {
		return fmt.Errorf("could not write array length: %s", err)
	}
	for _, elem := range m.Data {
		if err = ros.SerializeMessageField(w, "uint8", &elem); err != nil {
			return err
		}
	}

	return
}

func (m *LogData) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// Id
	if err = ros.DeserializeMessageField(r, "uint16", &m.Id); err != nil {
		return err
	}

	// Offset
	if err = ros.DeserializeMessageField(r, "uint32", &m.Offset); err != nil {
		return err
	}

	// Data
	{
		// Read size little endian
		var size uint32
		if err = binary.Read(r, binary.LittleEndian, &size); err != nil {
			return fmt.Errorf("cannot read array size for Data: %s", err)
		}
		m.Data = make([]uint8, int(size))
		for i := 0; i < int(size); i++ {
			if err = ros.DeserializeMessageField(r, "uint8", &m.Data[i]); err != nil {
				return err
			}
		}
	}

	return
}
