// Code generated by ros-gen-go.
// source: LogEntry.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgLogEntry struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgLogEntry) Text() string {
	return t.text
}

func (t *_MsgLogEntry) Name() string {
	return t.name
}

func (t *_MsgLogEntry) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgLogEntry) NewMessage() ros.Message {
	m := new(LogEntry)

	return m
}

var (
	MsgLogEntry = &_MsgLogEntry{
		`# Information about a single log
#
#  :id: - log id
#  :num_logs: - total number of logs
#  :last_log_num: - id of last log
#  :time_utc: - UTC timestamp of log (ros::Time(0) if not available)
#  :size: - size of log in bytes (may be approximate)

std_msgs/Header header

uint16 id
uint16 num_logs
uint16 last_log_num
time time_utc
uint32 size
`,
		"mavros_msgs/LogEntry",
		"a1428fc1ec4b2bfc8ab0c0ead7cce571",
	}
)

type LogEntry struct {
	Header     std_msgs.Header
	Id         uint16
	NumLogs    uint16
	LastLogNum uint16
	TimeUtc    ros.Time
	Size       uint32
}

func (m *LogEntry) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint16", &m.Id); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint16", &m.NumLogs); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint16", &m.LastLogNum); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "time", &m.TimeUtc); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint32", &m.Size); err != nil {
		return err
	}

	return
}

func (m *LogEntry) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// Id
	if err = ros.DeserializeMessageField(r, "uint16", &m.Id); err != nil {
		return err
	}

	// NumLogs
	if err = ros.DeserializeMessageField(r, "uint16", &m.NumLogs); err != nil {
		return err
	}

	// LastLogNum
	if err = ros.DeserializeMessageField(r, "uint16", &m.LastLogNum); err != nil {
		return err
	}

	// TimeUtc
	if err = ros.DeserializeMessageField(r, "time", &m.TimeUtc); err != nil {
		return err
	}

	// Size
	if err = ros.DeserializeMessageField(r, "uint32", &m.Size); err != nil {
		return err
	}

	return
}
