// Code generated by ros-gen-go.
// source: LogRequestList.srv
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

// Service type metadata
type _SrvLogRequestList struct {
	name    string
	md5sum  string
	text    string
	reqType ros.MessageType
	resType ros.MessageType
}

func (t *_SrvLogRequestList) Name() string                  { return t.name }
func (t *_SrvLogRequestList) MD5Sum() string                { return t.md5sum }
func (t *_SrvLogRequestList) Text() string                  { return t.text }
func (t *_SrvLogRequestList) RequestType() ros.MessageType  { return t.reqType }
func (t *_SrvLogRequestList) ResponseType() ros.MessageType { return t.resType }
func (t *_SrvLogRequestList) NewService() ros.Service {
	return new(LogRequestList)
}

var (
	SrvLogRequestList = &_SrvLogRequestList{
		"mavros_msgs/LogRequestList",
		"3e2e88c935b3047e14f450bc4a90c4d2",
		`# Request a list of available logs
#
#  :start: - first log id (0 for first available)
#  :end: - last log id (0xffff for last available)

uint16 start
uint16 end
---
bool success
`,
		MsgLogRequestListRequest,
		MsgLogRequestListResponse,
	}
)

type LogRequestList struct {
	Request  LogRequestListRequest
	Response LogRequestListResponse
}

func (s *LogRequestList) ReqMessage() ros.Message { return &s.Request }
func (s *LogRequestList) ResMessage() ros.Message { return &s.Response }

// LogRequestListRequest

type _MsgLogRequestListRequest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgLogRequestListRequest) Text() string {
	return t.text
}

func (t *_MsgLogRequestListRequest) Name() string {
	return t.name
}

func (t *_MsgLogRequestListRequest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgLogRequestListRequest) NewMessage() ros.Message {
	m := new(LogRequestListRequest)

	return m
}

var (
	MsgLogRequestListRequest = &_MsgLogRequestListRequest{
		`# Request a list of available logs
#
#  :start: - first log id (0 for first available)
#  :end: - last log id (0xffff for last available)

uint16 start
uint16 end
`,
		"mavros_msgs/LogRequestListRequest",
		"",
	}
)

type LogRequestListRequest struct {
	Start uint16
	End   uint16
}

func (m *LogRequestListRequest) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "uint16", &m.Start); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint16", &m.End); err != nil {
		return err
	}

	return
}

func (m *LogRequestListRequest) Deserialize(r io.Reader) (err error) {
	// Start
	if err = ros.DeserializeMessageField(r, "uint16", &m.Start); err != nil {
		return err
	}

	// End
	if err = ros.DeserializeMessageField(r, "uint16", &m.End); err != nil {
		return err
	}

	return
}

// LogRequestListResponse

type _MsgLogRequestListResponse struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgLogRequestListResponse) Text() string {
	return t.text
}

func (t *_MsgLogRequestListResponse) Name() string {
	return t.name
}

func (t *_MsgLogRequestListResponse) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgLogRequestListResponse) NewMessage() ros.Message {
	m := new(LogRequestListResponse)

	return m
}

var (
	MsgLogRequestListResponse = &_MsgLogRequestListResponse{
		`
bool success
`,
		"mavros_msgs/LogRequestListResponse",
		"",
	}
)

type LogRequestListResponse struct {
	Success bool
}

func (m *LogRequestListResponse) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.Success); err != nil {
		return err
	}

	return
}

func (m *LogRequestListResponse) Deserialize(r io.Reader) (err error) {
	// Success
	if err = ros.DeserializeMessageField(r, "bool", &m.Success); err != nil {
		return err
	}

	return
}
