// Code generated by ros-gen-go.
// source: LogRequestEnd.srv
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

// Service type metadata
type _SrvLogRequestEnd struct {
	name    string
	md5sum  string
	text    string
	reqType ros.MessageType
	resType ros.MessageType
}

func (t *_SrvLogRequestEnd) Name() string                  { return t.name }
func (t *_SrvLogRequestEnd) MD5Sum() string                { return t.md5sum }
func (t *_SrvLogRequestEnd) Text() string                  { return t.text }
func (t *_SrvLogRequestEnd) RequestType() ros.MessageType  { return t.reqType }
func (t *_SrvLogRequestEnd) ResponseType() ros.MessageType { return t.resType }
func (t *_SrvLogRequestEnd) NewService() ros.Service {
	return new(LogRequestEnd)
}

var (
	SrvLogRequestEnd = &_SrvLogRequestEnd{
		"mavros_msgs/LogRequestEnd",
		"358e233cde0c8a8bcfea4ce193f8fc15",
		`# Stop log transfer and resume normal logging

---
bool success
`,
		MsgLogRequestEndRequest,
		MsgLogRequestEndResponse,
	}
)

type LogRequestEnd struct {
	Request  LogRequestEndRequest
	Response LogRequestEndResponse
}

func (s *LogRequestEnd) ReqMessage() ros.Message { return &s.Request }
func (s *LogRequestEnd) ResMessage() ros.Message { return &s.Response }

// LogRequestEndRequest

type _MsgLogRequestEndRequest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgLogRequestEndRequest) Text() string {
	return t.text
}

func (t *_MsgLogRequestEndRequest) Name() string {
	return t.name
}

func (t *_MsgLogRequestEndRequest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgLogRequestEndRequest) NewMessage() ros.Message {
	m := new(LogRequestEndRequest)

	return m
}

var (
	MsgLogRequestEndRequest = &_MsgLogRequestEndRequest{
		`# Stop log transfer and resume normal logging

`,
		"mavros_msgs/LogRequestEndRequest",
		"",
	}
)

type LogRequestEndRequest struct {
}

func (m *LogRequestEndRequest) Serialize(w io.Writer) (err error) {
	return
}

func (m *LogRequestEndRequest) Deserialize(r io.Reader) (err error) {
	return
}

// LogRequestEndResponse

type _MsgLogRequestEndResponse struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgLogRequestEndResponse) Text() string {
	return t.text
}

func (t *_MsgLogRequestEndResponse) Name() string {
	return t.name
}

func (t *_MsgLogRequestEndResponse) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgLogRequestEndResponse) NewMessage() ros.Message {
	m := new(LogRequestEndResponse)

	return m
}

var (
	MsgLogRequestEndResponse = &_MsgLogRequestEndResponse{
		`
bool success
`,
		"mavros_msgs/LogRequestEndResponse",
		"",
	}
)

type LogRequestEndResponse struct {
	Success bool
}

func (m *LogRequestEndResponse) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.Success); err != nil {
		return err
	}

	return
}

func (m *LogRequestEndResponse) Deserialize(r io.Reader) (err error) {
	// Success
	if err = ros.DeserializeMessageField(r, "bool", &m.Success); err != nil {
		return err
	}

	return
}
