// Code generated by ros-gen-go.
// source: ManualControl.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgManualControl struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgManualControl) Text() string {
	return t.text
}

func (t *_MsgManualControl) Name() string {
	return t.name
}

func (t *_MsgManualControl) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgManualControl) NewMessage() ros.Message {
	m := new(ManualControl)

	return m
}

var (
	MsgManualControl = &_MsgManualControl{
		`# Manual Control state
std_msgs/Header header
float32 x
float32 y
float32 z
float32 r
uint16 buttons
`,
		"mavros_msgs/ManualControl",
		"c41e3298484ea98e05ac502ce55af59f",
	}
)

type ManualControl struct {
	Header  std_msgs.Header
	X       float32
	Y       float32
	Z       float32
	R       float32
	Buttons uint16
}

func (m *ManualControl) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.X); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Y); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Z); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.R); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint16", &m.Buttons); err != nil {
		return err
	}

	return
}

func (m *ManualControl) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// X
	if err = ros.DeserializeMessageField(r, "float32", &m.X); err != nil {
		return err
	}

	// Y
	if err = ros.DeserializeMessageField(r, "float32", &m.Y); err != nil {
		return err
	}

	// Z
	if err = ros.DeserializeMessageField(r, "float32", &m.Z); err != nil {
		return err
	}

	// R
	if err = ros.DeserializeMessageField(r, "float32", &m.R); err != nil {
		return err
	}

	// Buttons
	if err = ros.DeserializeMessageField(r, "uint16", &m.Buttons); err != nil {
		return err
	}

	return
}
