// Code generated by ros-gen-go.
// source: Param.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgParam struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgParam) Text() string {
	return t.text
}

func (t *_MsgParam) Name() string {
	return t.name
}

func (t *_MsgParam) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgParam) NewMessage() ros.Message {
	m := new(Param)

	return m
}

var (
	MsgParam = &_MsgParam{
		`# Parameter msg.

std_msgs/Header header

string param_id
mavros_msgs/ParamValue value

uint16 param_index
uint16 param_count
`,
		"mavros_msgs/Param",
		"62165a8f212050223dda9583b0f22c3c",
	}
)

type Param struct {
	Header     std_msgs.Header
	ParamId    string
	Value      ParamValue
	ParamIndex uint16
	ParamCount uint16
}

func (m *Param) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "string", &m.ParamId); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "mavros_msgs/ParamValue", &m.Value); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint16", &m.ParamIndex); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint16", &m.ParamCount); err != nil {
		return err
	}

	return
}

func (m *Param) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// ParamId
	if err = ros.DeserializeMessageField(r, "string", &m.ParamId); err != nil {
		return err
	}

	// Value
	if err = ros.DeserializeMessageField(r, "mavros_msgs/ParamValue", &m.Value); err != nil {
		return err
	}

	// ParamIndex
	if err = ros.DeserializeMessageField(r, "uint16", &m.ParamIndex); err != nil {
		return err
	}

	// ParamCount
	if err = ros.DeserializeMessageField(r, "uint16", &m.ParamCount); err != nil {
		return err
	}

	return
}
