// Code generated by ros-gen-go.
// source: ParamValue.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

type _MsgParamValue struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgParamValue) Text() string {
	return t.text
}

func (t *_MsgParamValue) Name() string {
	return t.name
}

func (t *_MsgParamValue) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgParamValue) NewMessage() ros.Message {
	m := new(ParamValue)

	return m
}

var (
	MsgParamValue = &_MsgParamValue{
		`# Parameter value storage type.
#
# Integer and float fields:
#
# if integer != 0: it is integer value
# else if real != 0.0: it is float value
# else: it is zero.

int64 integer
float64 real
`,
		"mavros_msgs/ParamValue",
		"e2cb1c7a0f6ef0c62d450cd9362c980d",
	}
)

type ParamValue struct {
	Integer int64
	Real    float64
}

func (m *ParamValue) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "int64", &m.Integer); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float64", &m.Real); err != nil {
		return err
	}

	return
}

func (m *ParamValue) Deserialize(r io.Reader) (err error) {
	// Integer
	if err = ros.DeserializeMessageField(r, "int64", &m.Integer); err != nil {
		return err
	}

	// Real
	if err = ros.DeserializeMessageField(r, "float64", &m.Real); err != nil {
		return err
	}

	return
}
