// Code generated by ros-gen-go.
// source: ParamPush.srv
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

// Service type metadata
type _SrvParamPush struct {
	name    string
	md5sum  string
	text    string
	reqType ros.MessageType
	resType ros.MessageType
}

func (t *_SrvParamPush) Name() string                  { return t.name }
func (t *_SrvParamPush) MD5Sum() string                { return t.md5sum }
func (t *_SrvParamPush) Text() string                  { return t.text }
func (t *_SrvParamPush) RequestType() ros.MessageType  { return t.reqType }
func (t *_SrvParamPush) ResponseType() ros.MessageType { return t.resType }
func (t *_SrvParamPush) NewService() ros.Service {
	return new(ParamPush)
}

var (
	SrvParamPush = &_SrvParamPush{
		"mavros_msgs/ParamPush",
		"d3fc4d8cefa193382985a92a041a2a3d",
		`# Send current send
#
# Returns success status and param_transfered count

---
bool success
uint32 param_transfered
`,
		MsgParamPushRequest,
		MsgParamPushResponse,
	}
)

type ParamPush struct {
	Request  ParamPushRequest
	Response ParamPushResponse
}

func (s *ParamPush) ReqMessage() ros.Message { return &s.Request }
func (s *ParamPush) ResMessage() ros.Message { return &s.Response }

// ParamPushRequest

type _MsgParamPushRequest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgParamPushRequest) Text() string {
	return t.text
}

func (t *_MsgParamPushRequest) Name() string {
	return t.name
}

func (t *_MsgParamPushRequest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgParamPushRequest) NewMessage() ros.Message {
	m := new(ParamPushRequest)

	return m
}

var (
	MsgParamPushRequest = &_MsgParamPushRequest{
		`# Send current send
#
# Returns success status and param_transfered count

`,
		"mavros_msgs/ParamPushRequest",
		"",
	}
)

type ParamPushRequest struct {
}

func (m *ParamPushRequest) Serialize(w io.Writer) (err error) {
	return
}

func (m *ParamPushRequest) Deserialize(r io.Reader) (err error) {
	return
}

// ParamPushResponse

type _MsgParamPushResponse struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgParamPushResponse) Text() string {
	return t.text
}

func (t *_MsgParamPushResponse) Name() string {
	return t.name
}

func (t *_MsgParamPushResponse) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgParamPushResponse) NewMessage() ros.Message {
	m := new(ParamPushResponse)

	return m
}

var (
	MsgParamPushResponse = &_MsgParamPushResponse{
		`
bool success
uint32 param_transfered
`,
		"mavros_msgs/ParamPushResponse",
		"",
	}
)

type ParamPushResponse struct {
	Success         bool
	ParamTransfered uint32
}

func (m *ParamPushResponse) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.Success); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint32", &m.ParamTransfered); err != nil {
		return err
	}

	return
}

func (m *ParamPushResponse) Deserialize(r io.Reader) (err error) {
	// Success
	if err = ros.DeserializeMessageField(r, "bool", &m.Success); err != nil {
		return err
	}

	// ParamTransfered
	if err = ros.DeserializeMessageField(r, "uint32", &m.ParamTransfered); err != nil {
		return err
	}

	return
}
