// Code generated by ros-gen-go.
// source: ParamSet.srv
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

// Service type metadata
type _SrvParamSet struct {
	name    string
	md5sum  string
	text    string
	reqType ros.MessageType
	resType ros.MessageType
}

func (t *_SrvParamSet) Name() string                  { return t.name }
func (t *_SrvParamSet) MD5Sum() string                { return t.md5sum }
func (t *_SrvParamSet) Text() string                  { return t.text }
func (t *_SrvParamSet) RequestType() ros.MessageType  { return t.reqType }
func (t *_SrvParamSet) ResponseType() ros.MessageType { return t.resType }
func (t *_SrvParamSet) NewService() ros.Service {
	return new(ParamSet)
}

var (
	SrvParamSet = &_SrvParamSet{
		"mavros_msgs/ParamSet",
		"c423cafb898fff374cbe8530ecd4d285",
		`# Request set parameter value

string param_id
mavros_msgs/ParamValue value
---
bool success
mavros_msgs/ParamValue value
`,
		MsgParamSetRequest,
		MsgParamSetResponse,
	}
)

type ParamSet struct {
	Request  ParamSetRequest
	Response ParamSetResponse
}

func (s *ParamSet) ReqMessage() ros.Message { return &s.Request }
func (s *ParamSet) ResMessage() ros.Message { return &s.Response }

// ParamSetRequest

type _MsgParamSetRequest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgParamSetRequest) Text() string {
	return t.text
}

func (t *_MsgParamSetRequest) Name() string {
	return t.name
}

func (t *_MsgParamSetRequest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgParamSetRequest) NewMessage() ros.Message {
	m := new(ParamSetRequest)

	return m
}

var (
	MsgParamSetRequest = &_MsgParamSetRequest{
		`# Request set parameter value

string param_id
mavros_msgs/ParamValue value
`,
		"mavros_msgs/ParamSetRequest",
		"c423cafb898fff374cbe8530ecd4d285",
	}
)

type ParamSetRequest struct {
	ParamId string
	Value   ParamValue
}

func (m *ParamSetRequest) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "string", &m.ParamId); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "mavros_msgs/ParamValue", &m.Value); err != nil {
		return err
	}

	return
}

func (m *ParamSetRequest) Deserialize(r io.Reader) (err error) {
	// ParamId
	if err = ros.DeserializeMessageField(r, "string", &m.ParamId); err != nil {
		return err
	}

	// Value
	if err = ros.DeserializeMessageField(r, "mavros_msgs/ParamValue", &m.Value); err != nil {
		return err
	}

	return
}

// ParamSetResponse

type _MsgParamSetResponse struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgParamSetResponse) Text() string {
	return t.text
}

func (t *_MsgParamSetResponse) Name() string {
	return t.name
}

func (t *_MsgParamSetResponse) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgParamSetResponse) NewMessage() ros.Message {
	m := new(ParamSetResponse)

	return m
}

var (
	MsgParamSetResponse = &_MsgParamSetResponse{
		`
bool success
mavros_msgs/ParamValue value
`,
		"mavros_msgs/ParamSetResponse",
		"c423cafb898fff374cbe8530ecd4d285",
	}
)

type ParamSetResponse struct {
	Success bool
	Value   ParamValue
}

func (m *ParamSetResponse) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.Success); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "mavros_msgs/ParamValue", &m.Value); err != nil {
		return err
	}

	return
}

func (m *ParamSetResponse) Deserialize(r io.Reader) (err error) {
	// Success
	if err = ros.DeserializeMessageField(r, "bool", &m.Success); err != nil {
		return err
	}

	// Value
	if err = ros.DeserializeMessageField(r, "mavros_msgs/ParamValue", &m.Value); err != nil {
		return err
	}

	return
}
