// Code generated by ros-gen-go.
// source: ParamPull.srv
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

// Service type metadata
type _SrvParamPull struct {
	name    string
	md5sum  string
	text    string
	reqType ros.MessageType
	resType ros.MessageType
}

func (t *_SrvParamPull) Name() string                  { return t.name }
func (t *_SrvParamPull) MD5Sum() string                { return t.md5sum }
func (t *_SrvParamPull) Text() string                  { return t.text }
func (t *_SrvParamPull) RequestType() ros.MessageType  { return t.reqType }
func (t *_SrvParamPull) ResponseType() ros.MessageType { return t.resType }
func (t *_SrvParamPull) NewService() ros.Service {
	return new(ParamPull)
}

var (
	SrvParamPull = &_SrvParamPull{
		"mavros_msgs/ParamPull",
		"c9628aea2226088718fd240fbd62afc7",
		`# Request parameters from device
#
# Returns success status and param_recived count

bool force_pull
---
bool success
uint32 param_received
`,
		MsgParamPullRequest,
		MsgParamPullResponse,
	}
)

type ParamPull struct {
	Request  ParamPullRequest
	Response ParamPullResponse
}

func (s *ParamPull) ReqMessage() ros.Message { return &s.Request }
func (s *ParamPull) ResMessage() ros.Message { return &s.Response }

// ParamPullRequest

type _MsgParamPullRequest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgParamPullRequest) Text() string {
	return t.text
}

func (t *_MsgParamPullRequest) Name() string {
	return t.name
}

func (t *_MsgParamPullRequest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgParamPullRequest) NewMessage() ros.Message {
	m := new(ParamPullRequest)

	return m
}

var (
	MsgParamPullRequest = &_MsgParamPullRequest{
		`# Request parameters from device
#
# Returns success status and param_recived count

bool force_pull
`,
		"mavros_msgs/ParamPullRequest",
		"",
	}
)

type ParamPullRequest struct {
	ForcePull bool
}

func (m *ParamPullRequest) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.ForcePull); err != nil {
		return err
	}

	return
}

func (m *ParamPullRequest) Deserialize(r io.Reader) (err error) {
	// ForcePull
	if err = ros.DeserializeMessageField(r, "bool", &m.ForcePull); err != nil {
		return err
	}

	return
}

// ParamPullResponse

type _MsgParamPullResponse struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgParamPullResponse) Text() string {
	return t.text
}

func (t *_MsgParamPullResponse) Name() string {
	return t.name
}

func (t *_MsgParamPullResponse) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgParamPullResponse) NewMessage() ros.Message {
	m := new(ParamPullResponse)

	return m
}

var (
	MsgParamPullResponse = &_MsgParamPullResponse{
		`
bool success
uint32 param_received
`,
		"mavros_msgs/ParamPullResponse",
		"",
	}
)

type ParamPullResponse struct {
	Success       bool
	ParamReceived uint32
}

func (m *ParamPullResponse) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.Success); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint32", &m.ParamReceived); err != nil {
		return err
	}

	return
}

func (m *ParamPullResponse) Deserialize(r io.Reader) (err error) {
	// Success
	if err = ros.DeserializeMessageField(r, "bool", &m.Success); err != nil {
		return err
	}

	// ParamReceived
	if err = ros.DeserializeMessageField(r, "uint32", &m.ParamReceived); err != nil {
		return err
	}

	return
}
