// Code generated by ros-gen-go.
// source: RadioStatus.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgRadioStatus struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgRadioStatus) Text() string {
	return t.text
}

func (t *_MsgRadioStatus) Name() string {
	return t.name
}

func (t *_MsgRadioStatus) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgRadioStatus) NewMessage() ros.Message {
	m := new(RadioStatus)

	return m
}

var (
	MsgRadioStatus = &_MsgRadioStatus{
		`# RADIO_STATUS message

std_msgs/Header header

# message data
uint8 rssi
uint8 remrssi
uint8 txbuf
uint8 noise
uint8 remnoise
uint16 rxerrors
uint16 fixed

# calculated
float32 rssi_dbm
float32 remrssi_dbm
`,
		"mavros_msgs/RadioStatus",
		"04e4a879bb2687140da50a1a821e2190",
	}
)

type RadioStatus struct {
	Header     std_msgs.Header
	Rssi       uint8
	Remrssi    uint8
	Txbuf      uint8
	Noise      uint8
	Remnoise   uint8
	Rxerrors   uint16
	Fixed      uint16
	RssiDbm    float32
	RemrssiDbm float32
}

func (m *RadioStatus) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint8", &m.Rssi); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint8", &m.Remrssi); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint8", &m.Txbuf); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint8", &m.Noise); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint8", &m.Remnoise); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint16", &m.Rxerrors); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint16", &m.Fixed); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.RssiDbm); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.RemrssiDbm); err != nil {
		return err
	}

	return
}

func (m *RadioStatus) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// Rssi
	if err = ros.DeserializeMessageField(r, "uint8", &m.Rssi); err != nil {
		return err
	}

	// Remrssi
	if err = ros.DeserializeMessageField(r, "uint8", &m.Remrssi); err != nil {
		return err
	}

	// Txbuf
	if err = ros.DeserializeMessageField(r, "uint8", &m.Txbuf); err != nil {
		return err
	}

	// Noise
	if err = ros.DeserializeMessageField(r, "uint8", &m.Noise); err != nil {
		return err
	}

	// Remnoise
	if err = ros.DeserializeMessageField(r, "uint8", &m.Remnoise); err != nil {
		return err
	}

	// Rxerrors
	if err = ros.DeserializeMessageField(r, "uint16", &m.Rxerrors); err != nil {
		return err
	}

	// Fixed
	if err = ros.DeserializeMessageField(r, "uint16", &m.Fixed); err != nil {
		return err
	}

	// RssiDbm
	if err = ros.DeserializeMessageField(r, "float32", &m.RssiDbm); err != nil {
		return err
	}

	// RemrssiDbm
	if err = ros.DeserializeMessageField(r, "float32", &m.RemrssiDbm); err != nil {
		return err
	}

	return
}
