// Code generated by ros-gen-go.
// source: RCOut.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"encoding/binary"
	"fmt"
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgRCOut struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgRCOut) Text() string {
	return t.text
}

func (t *_MsgRCOut) Name() string {
	return t.name
}

func (t *_MsgRCOut) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgRCOut) NewMessage() ros.Message {
	m := new(RCOut)

	return m
}

var (
	MsgRCOut = &_MsgRCOut{
		`# RAW Servo out state

std_msgs/Header header
uint16[] channels
`,
		"mavros_msgs/RCOut",
		"52cacf104bab5ae3b103cfe176590713",
	}
)

type RCOut struct {
	Header   std_msgs.Header
	Channels []uint16
}

func (m *RCOut) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// Write size little endian
	err = binary.Write(w, binary.LittleEndian, uint32(len(m.Channels)))
	if err != nil {
		return fmt.Errorf("could not write array length: %s", err)
	}
	for _, elem := range m.Channels {
		if err = ros.SerializeMessageField(w, "uint16", &elem); err != nil {
			return err
		}
	}

	return
}

func (m *RCOut) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// Channels
	{
		// Read size little endian
		var size uint32
		if err = binary.Read(r, binary.LittleEndian, &size); err != nil {
			return fmt.Errorf("cannot read array size for Channels: %s", err)
		}
		m.Channels = make([]uint16, int(size))
		for i := 0; i < int(size); i++ {
			if err = ros.DeserializeMessageField(r, "uint16", &m.Channels[i]); err != nil {
				return err
			}
		}
	}

	return
}
