// Code generated by ros-gen-go.
// source: SetMode.srv
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/ros"
)

// Service type metadata
type _SrvSetMode struct {
	name    string
	md5sum  string
	text    string
	reqType ros.MessageType
	resType ros.MessageType
}

func (t *_SrvSetMode) Name() string                  { return t.name }
func (t *_SrvSetMode) MD5Sum() string                { return t.md5sum }
func (t *_SrvSetMode) Text() string                  { return t.text }
func (t *_SrvSetMode) RequestType() ros.MessageType  { return t.reqType }
func (t *_SrvSetMode) ResponseType() ros.MessageType { return t.resType }
func (t *_SrvSetMode) NewService() ros.Service {
	return new(SetMode)
}

var (
	SrvSetMode = &_SrvSetMode{
		"mavros_msgs/SetMode",
		"e4f18fa93379f9ff1780d270ce110203",
		`# set FCU mode
#
# Known custom modes listed here:
# http://wiki.ros.org/mavros/CustomModes

# basic modes from MAV_MODE
uint8 MAV_MODE_PREFLIGHT		= 0
uint8 MAV_MODE_STABILIZE_DISARMED	= 80
uint8 MAV_MODE_STABILIZE_ARMED		= 208
uint8 MAV_MODE_MANUAL_DISARMED		= 64
uint8 MAV_MODE_MANUAL_ARMED		= 192
uint8 MAV_MODE_GUIDED_DISARMED		= 88
uint8 MAV_MODE_GUIDED_ARMED		= 216
uint8 MAV_MODE_AUTO_DISARMED		= 92
uint8 MAV_MODE_AUTO_ARMED		= 220
uint8 MAV_MODE_TEST_DISARMED		= 66
uint8 MAV_MODE_TEST_ARMED		= 194

uint8 base_mode		# filled by MAV_MODE enum value or 0 if custom_mode != ''
string custom_mode	# string mode representation or integer
---
bool mode_sent		# Mode known/parsed correctly and SET_MODE are sent
`,
		MsgSetModeRequest,
		MsgSetModeResponse,
	}
)

type SetMode struct {
	Request  SetModeRequest
	Response SetModeResponse
}

func (s *SetMode) ReqMessage() ros.Message { return &s.Request }
func (s *SetMode) ResMessage() ros.Message { return &s.Response }

// SetModeRequest

type _MsgSetModeRequest struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgSetModeRequest) Text() string {
	return t.text
}

func (t *_MsgSetModeRequest) Name() string {
	return t.name
}

func (t *_MsgSetModeRequest) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgSetModeRequest) NewMessage() ros.Message {
	m := new(SetModeRequest)

	return m
}

var (
	MsgSetModeRequest = &_MsgSetModeRequest{
		`# set FCU mode
#
# Known custom modes listed here:
# http://wiki.ros.org/mavros/CustomModes

# basic modes from MAV_MODE
uint8 MAV_MODE_PREFLIGHT		= 0
uint8 MAV_MODE_STABILIZE_DISARMED	= 80
uint8 MAV_MODE_STABILIZE_ARMED		= 208
uint8 MAV_MODE_MANUAL_DISARMED		= 64
uint8 MAV_MODE_MANUAL_ARMED		= 192
uint8 MAV_MODE_GUIDED_DISARMED		= 88
uint8 MAV_MODE_GUIDED_ARMED		= 216
uint8 MAV_MODE_AUTO_DISARMED		= 92
uint8 MAV_MODE_AUTO_ARMED		= 220
uint8 MAV_MODE_TEST_DISARMED		= 66
uint8 MAV_MODE_TEST_ARMED		= 194

uint8 base_mode		# filled by MAV_MODE enum value or 0 if custom_mode != ''
string custom_mode	# string mode representation or integer
`,
		"mavros_msgs/SetModeRequest",
		"e4f18fa93379f9ff1780d270ce110203",
	}
)

type SetModeRequest struct {
	BaseMode   uint8
	CustomMode string
}

func (m *SetModeRequest) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "uint8", &m.BaseMode); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "string", &m.CustomMode); err != nil {
		return err
	}

	return
}

func (m *SetModeRequest) Deserialize(r io.Reader) (err error) {
	// BaseMode
	if err = ros.DeserializeMessageField(r, "uint8", &m.BaseMode); err != nil {
		return err
	}

	// CustomMode
	if err = ros.DeserializeMessageField(r, "string", &m.CustomMode); err != nil {
		return err
	}

	return
}

// SetModeResponse

type _MsgSetModeResponse struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgSetModeResponse) Text() string {
	return t.text
}

func (t *_MsgSetModeResponse) Name() string {
	return t.name
}

func (t *_MsgSetModeResponse) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgSetModeResponse) NewMessage() ros.Message {
	m := new(SetModeResponse)

	return m
}

var (
	MsgSetModeResponse = &_MsgSetModeResponse{
		`
bool mode_sent		# Mode known/parsed correctly and SET_MODE are sent
`,
		"mavros_msgs/SetModeResponse",
		"e4f18fa93379f9ff1780d270ce110203",
	}
)

type SetModeResponse struct {
	ModeSent bool
}

func (m *SetModeResponse) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "bool", &m.ModeSent); err != nil {
		return err
	}

	return
}

func (m *SetModeResponse) Deserialize(r io.Reader) (err error) {
	// ModeSent
	if err = ros.DeserializeMessageField(r, "bool", &m.ModeSent); err != nil {
		return err
	}

	return
}
