// Code generated by ros-gen-go.
// source: State.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgState struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgState) Text() string {
	return t.text
}

func (t *_MsgState) Name() string {
	return t.name
}

func (t *_MsgState) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgState) NewMessage() ros.Message {
	m := new(State)

	return m
}

var (
	MsgState = &_MsgState{
		`# Current autopilot state
#
# Known modes listed here:
# http://wiki.ros.org/mavros/CustomModes
#
# For system_status values
# see http://mavlink.org/messages/common MAV_STATE
#

std_msgs/Header header
bool connected
bool armed
bool guided
string mode
uint8 system_status
`,
		"mavros_msgs/State",
		"63d9a29b6abd9e0beeba06109556d062",
	}
)

type State struct {
	Header       std_msgs.Header
	Connected    bool
	Armed        bool
	Guided       bool
	Mode         string
	SystemStatus uint8
}

func (m *State) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "bool", &m.Connected); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "bool", &m.Armed); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "bool", &m.Guided); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "string", &m.Mode); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "uint8", &m.SystemStatus); err != nil {
		return err
	}

	return
}

func (m *State) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// Connected
	if err = ros.DeserializeMessageField(r, "bool", &m.Connected); err != nil {
		return err
	}

	// Armed
	if err = ros.DeserializeMessageField(r, "bool", &m.Armed); err != nil {
		return err
	}

	// Guided
	if err = ros.DeserializeMessageField(r, "bool", &m.Guided); err != nil {
		return err
	}

	// Mode
	if err = ros.DeserializeMessageField(r, "string", &m.Mode); err != nil {
		return err
	}

	// SystemStatus
	if err = ros.DeserializeMessageField(r, "uint8", &m.SystemStatus); err != nil {
		return err
	}

	return
}
