// Code generated by ros-gen-go.
// source: Thrust.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgThrust struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgThrust) Text() string {
	return t.text
}

func (t *_MsgThrust) Name() string {
	return t.name
}

func (t *_MsgThrust) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgThrust) NewMessage() ros.Message {
	m := new(Thrust)

	return m
}

var (
	MsgThrust = &_MsgThrust{
		`# Thrust to send to the FCU

std_msgs/Header header

float32 thrust
`,
		"mavros_msgs/Thrust",
		"c61da3a8868a8b502eaf0b0abd839f57",
	}
)

type Thrust struct {
	Header std_msgs.Header
	Thrust float32
}

func (m *Thrust) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	if err = ros.SerializeMessageField(w, "float32", &m.Thrust); err != nil {
		return err
	}

	return
}

func (m *Thrust) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// Thrust
	if err = ros.DeserializeMessageField(r, "float32", &m.Thrust); err != nil {
		return err
	}

	return
}
