// Code generated by ros-gen-go.
// source: WheelOdomStamped.msg
// DO NOT EDIT!
package mavros_msgs

import (
	"encoding/binary"
	"fmt"
	"io"

	"github.com/cnord/rosgo/msgs/std_msgs"
	"github.com/cnord/rosgo/ros"
)

type _MsgWheelOdomStamped struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgWheelOdomStamped) Text() string {
	return t.text
}

func (t *_MsgWheelOdomStamped) Name() string {
	return t.name
}

func (t *_MsgWheelOdomStamped) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgWheelOdomStamped) NewMessage() ros.Message {
	m := new(WheelOdomStamped)

	return m
}

var (
	MsgWheelOdomStamped = &_MsgWheelOdomStamped{
		`# Stamped wheel odometry message
#
# For streaming timestamped data from FCU wheel encoders (RPM or WHEEL_DISTANCE).

std_msgs/Header header
float64[] data
`,
		"mavros_msgs/WheelOdomStamped",
		"fb60495edd59d3fcf90e173153ae8a9a",
	}
)

type WheelOdomStamped struct {
	Header std_msgs.Header
	Data   []float64
}

func (m *WheelOdomStamped) Serialize(w io.Writer) (err error) {
	if err = ros.SerializeMessageField(w, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// Write size little endian
	err = binary.Write(w, binary.LittleEndian, uint32(len(m.Data)))
	if err != nil {
		return fmt.Errorf("could not write array length: %s", err)
	}
	for _, elem := range m.Data {
		if err = ros.SerializeMessageField(w, "float64", &elem); err != nil {
			return err
		}
	}

	return
}

func (m *WheelOdomStamped) Deserialize(r io.Reader) (err error) {
	// Header
	if err = ros.DeserializeMessageField(r, "std_msgs/Header", &m.Header); err != nil {
		return err
	}

	// Data
	{
		// Read size little endian
		var size uint32
		if err = binary.Read(r, binary.LittleEndian, &size); err != nil {
			return fmt.Errorf("cannot read array size for Data: %s", err)
		}
		m.Data = make([]float64, int(size))
		for i := 0; i < int(size); i++ {
			if err = ros.DeserializeMessageField(r, "float64", &m.Data[i]); err != nil {
				return err
			}
		}
	}

	return
}
